<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Confidence Intervals | Book.knit</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Confidence Intervals | Book.knit" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Confidence Intervals | Book.knit" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="foundations-of-inference.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>STA258: Statistics with Applied Probability</a></li>
<li class="chapter" data-level="" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html"><i class="fa fa-check"></i>Introduction and Overview</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#sec:foundations"><i class="fa fa-check"></i><b>1.1</b> Foundations</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#types-of-data"><i class="fa fa-check"></i><b>1.2</b> Types of data</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#introduction-to-inferential-statistics"><i class="fa fa-check"></i><b>1.3</b> Introduction to Inferential statistics</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html"><i class="fa fa-check"></i><b>2</b> An Introduction to R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#the-statistical-computing-language"><i class="fa fa-check"></i><b>2.1</b> The Statistical Computing Language</a></li>
<li class="chapter" data-level="2.2" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>2.2</b> Installing R and RStudio</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#installing-r"><i class="fa fa-check"></i><b>2.2.1</b> Installing R</a></li>
<li class="chapter" data-level="2.2.2" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#installing-rstudio"><i class="fa fa-check"></i><b>2.2.2</b> Installing RStudio</a></li>
<li class="chapter" data-level="2.2.3" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#what-is-posit-and-positron"><i class="fa fa-check"></i><b>2.2.3</b> What Is Posit and Positron?</a></li>
<li class="chapter" data-level="2.2.4" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#make-a-histogram-using-rstudio"><i class="fa fa-check"></i><b>2.2.4</b> Make a Histogram Using RStudio</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>3</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#representing-data"><i class="fa fa-check"></i><b>3.1</b> Representing Data</a></li>
<li class="chapter" data-level="3.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#numerical-measures"><i class="fa fa-check"></i><b>3.2</b> Numerical Measures</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mean"><i class="fa fa-check"></i><b>3.2.1</b> Mean</a></li>
<li class="chapter" data-level="3.2.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#median"><i class="fa fa-check"></i><b>3.2.2</b> Median</a></li>
<li class="chapter" data-level="3.2.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mode"><i class="fa fa-check"></i><b>3.2.3</b> Mode</a></li>
<li class="chapter" data-level="3.2.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#variance"><i class="fa fa-check"></i><b>3.2.4</b> Variance</a></li>
<li class="chapter" data-level="3.2.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#standard-deviation"><i class="fa fa-check"></i><b>3.2.5</b> Standard Deviation</a></li>
<li class="chapter" data-level="3.2.6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#range"><i class="fa fa-check"></i><b>3.2.6</b> Range</a></li>
<li class="chapter" data-level="3.2.7" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#percentiles"><i class="fa fa-check"></i><b>3.2.7</b> Percentiles</a></li>
<li class="chapter" data-level="3.2.8" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#quartiles"><i class="fa fa-check"></i><b>3.2.8</b> Quartiles</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#sec:GraphicalTechniques"><i class="fa fa-check"></i><b>3.3</b> Grapchical Techniques</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#histograms"><i class="fa fa-check"></i><b>3.3.1</b> Histograms</a></li>
<li class="chapter" data-level="3.3.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#boxplots"><i class="fa fa-check"></i><b>3.3.2</b> Boxplots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html"><i class="fa fa-check"></i><b>4</b> Foundations of Inference</a>
<ul>
<li class="chapter" data-level="4.1" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#sec:inference"><i class="fa fa-check"></i><b>4.1</b> Some Important Statistical Distributions</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#sec:IntroNormalDist"><i class="fa fa-check"></i><b>4.1.1</b> Introduction to the Normal Distribution</a></li>
<li class="chapter" data-level="4.1.2" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#introduction-to-the-chi-square-distribution"><i class="fa fa-check"></i><b>4.1.2</b> Introduction to the Chi-Square distribution</a></li>
<li class="chapter" data-level="4.1.3" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#introduction-to-the-t-distribution"><i class="fa fa-check"></i><b>4.1.3</b> Introduction to the t-Distribution</a></li>
<li class="chapter" data-level="4.1.4" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#introduction-to-the-f-distribution"><i class="fa fa-check"></i><b>4.1.4</b> Introduction to the F-Distribution</a></li>
<li class="chapter" data-level="4.1.5" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#arithmetics-of-rvs"><i class="fa fa-check"></i><b>4.1.5</b> Arithmetics of RV’s</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#sampling-distributions"><i class="fa fa-check"></i><b>4.2</b> Sampling Distributions</a></li>
<li class="chapter" data-level="4.3" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>4.3</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="4.4" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#law-of-large-numbers"><i class="fa fa-check"></i><b>4.4</b> Law of Large Numbers</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#convergence-in-probability"><i class="fa fa-check"></i><b>4.4.1</b> Convergence in Probability</a></li>
<li class="chapter" data-level="4.4.2" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#weak-law-of-large-numbers-wlln"><i class="fa fa-check"></i><b>4.4.2</b> Weak Law of Large Numbers (WLLN)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="confidence-intervals.html"><a href="confidence-intervals.html"><i class="fa fa-check"></i><b>5</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="5.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#introduction-1"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#interpretation"><i class="fa fa-check"></i><b>5.2</b> Interpretation</a></li>
<li class="chapter" data-level="5.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#one-sample-confidence-intervals"><i class="fa fa-check"></i><b>5.3</b> One Sample Confidence Intervals</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#on-a-population-mean"><i class="fa fa-check"></i><b>5.3.1</b> On a Population Mean</a></li>
<li class="chapter" data-level="5.3.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#on-a-population-proportion"><i class="fa fa-check"></i><b>5.3.2</b> On a Population Proportion</a></li>
<li class="chapter" data-level="5.3.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#on-a-population-variance"><i class="fa fa-check"></i><b>5.3.3</b> On a Population Variance</a></li>
<li class="chapter" data-level="5.3.4" data-path="confidence-intervals.html"><a href="confidence-intervals.html#assumptions"><i class="fa fa-check"></i><b>5.3.4</b> Assumptions</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="confidence-intervals.html"><a href="confidence-intervals.html#two-sample-confidence-intervals"><i class="fa fa-check"></i><b>5.4</b> Two Sample Confidence Intervals</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#on-a-difference-of-means"><i class="fa fa-check"></i><b>5.4.1</b> On a Difference of Means</a></li>
<li class="chapter" data-level="5.4.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#on-a-difference-of-proportions"><i class="fa fa-check"></i><b>5.4.2</b> On a Difference of Proportions</a></li>
<li class="chapter" data-level="5.4.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#on-a-ratio-of-variances"><i class="fa fa-check"></i><b>5.4.3</b> On a Ratio of Variances</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="confidence-intervals.html"><a href="confidence-intervals.html#confidence-intervals-on-paired-data"><i class="fa fa-check"></i><b>5.5</b> Confidence Intervals on Paired Data</a></li>
<li class="chapter" data-level="5.6" data-path="confidence-intervals.html"><a href="confidence-intervals.html#sample-size-selection-using-confidence-intervals"><i class="fa fa-check"></i><b>5.6</b> Sample Size Selection using Confidence Intervals</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#secSampleSizeCIMean"><i class="fa fa-check"></i><b>5.6.1</b> Calculating Sample Size for a Confidence Interval on a Mean</a></li>
<li class="chapter" data-level="5.6.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#calculating-sample-size-for-a-confidence-interval-on-a-proportion"><i class="fa fa-check"></i><b>5.6.2</b> Calculating Sample Size for a Confidence Interval on a Proportion</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="confidence-intervals" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Chapter 5</span> Confidence Intervals<a href="confidence-intervals.html#confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introduction-1" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Introduction<a href="confidence-intervals.html#introduction-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Confidence intervals are a fundamental concept in statistics that allow us to make inferences about a population based on a sample. They provide a range of values, derived from the sample data, that is likely to contain the true population parameter with a specified level of confidence.</p>
<p>We will start by introducing point estimates which are used to estimate population parameters and then move on to interval estimates which utilzie point estimates to calculate them.</p>
<div class="definition" Name="Point Estimate">
<p><span id="def:PointEstim" class="definition"><strong>Definition 5.1  </strong></span>A point estimate is a single numerical value computed from sample data that serves as the best guess of an unknown population parameter.</p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-27" class="example"><strong>Example 5.1  </strong></span></p>
<ul>
<li><span class="math inline">\(\bar{x}\)</span> is a point estimate of <span class="math inline">\(\mu\)</span></li>
<li><span class="math inline">\(s^2\)</span> is a point estimate of <span class="math inline">\(\sigma^2\)</span></li>
<li><span class="math inline">\(s\)</span> is a point estimate of <span class="math inline">\(\sigma\)</span></li>
</ul>
</div>
<p>Recall in Section <a href="foundations-of-inference.html#sec:inference">4.1</a> where we introduced statistics inference,
we discussed that we the values of statistics which are calculated and known
to make conclusions on parameters which are unknown and quantify the degree of
certainty of statements
made.</p>
<p>When we calculate a statistic, it will not be exactly equal to the parameter it is estimating.
For example, the sample mean <span class="math inline">\(\bar{x}\)</span> is not exactly equal to the population mean <span class="math inline">\(\mu\)</span>.
We can get an idea about the value of a parameter using an
<em>interval estimate</em> which gives a <em>range of real numbers</em> around the statistic
which we believe contains it.</p>
<div class="definition">
<p><span id="def:unlabeled-div-28" class="definition"><strong>Definition 5.2  </strong></span>A confidence interval is a plausible range of values that captures a
parameter with a quantified degree of confidence.</p>
</div>
<p>In this course, all confidence intervals have the same basic skeleton:</p>
<p><span class="math display">\[\text{estimator} \pm
\underbrace{
\left(
\text{value from a reference distribution}
\right)
\times
\left(
\text{standard error of estimate}
\right)
}_{\textit{margin of error}}\]</span></p>
<p>The <em>standard error of the estimator</em> is the standard deviation of the
the <em>sampling distribution</em> of the estimator.</p>
<p>The value from the reference distribution in the skeleton above will be
either a value from the standard normal distribution the Student
<em>t</em>-distribution, ot the chi-square distribution.
The margin of error (<em>MOE</em>) can be considered as the
distance around our estimator in which the true value of the parameter
of interest will be found, with a specified level of confidence.</p>
</div>
<div id="interpretation" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Interpretation<a href="confidence-intervals.html#interpretation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We use very specific language when we interpret a confidence interval.</p>
<div class="tcolorbox">
<p><em>Suppose we construct a <span class="math inline">\(C\%\)</span> confidence interval for some parameter
such that <span class="math inline">\(C\)</span> is between 0 and 100. In repeated sampling, we are <span class="math inline">\(C\%\)</span>
confident that approximately <span class="math inline">\(C\%\)</span> of the intervals will capture the
true value of the parameter.</em></p>
</div>
<p>By this we mean that if we constructed several <span class="math inline">\(C\%\)</span> confidence
intervals using different samples (with or without replacing the units),
then we should expect approximately <span class="math inline">\(C\%\)</span> of these intervals to capture
the parameter of interest. For example suppose we construct 1000 95%
confidence intervals for the population mean <span class="math inline">\(\mu\)</span>. We would expect
approximately 95% of these 1000 intervals
(i.e. <span class="math inline">\(95\% \times 1000 = 950\)</span>) to actually capture <span class="math inline">\(\mu\)</span>.</p>
<p>A more intuitive but equivalent interpretation is to state that we are
<span class="math inline">\(C\)</span>% confident that our target parameter is inside the interval
constructed.</p>
<div class="remark">
<p><span id="unlabeled-div-29" class="remark"><em>Remark</em>. </span>It is <strong>incorrect</strong> to state that there is a <span class="math inline">\(C\%\)</span> probability that the
interval we constructed contains the parameter of interest. We assume
that the value of a parameter is fixed. Therefore when we construct a
confidence interval, the interval either contains the parameter or it
does not.</p>
</div>
<p>Not all confidence intervals contain the true value of the parameter. This can be
illustrated by plotting many intervals simultaneously and observing.</p>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-8"></span>
<img src="Book_Files/figure-html/unnamed-chunk-8-1.png" alt="Simulated 95% confidence intervals for the population mean" width="672" />
<p class="caption">
Figure 5.1: Simulated 95% confidence intervals for the population mean
</p>
</div>
</div>
<div id="one-sample-confidence-intervals" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> One Sample Confidence Intervals<a href="confidence-intervals.html#one-sample-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section, we will focus on constructing confidence intervals for one parameter.</p>
<div id="on-a-population-mean" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> On a Population Mean<a href="confidence-intervals.html#on-a-population-mean" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="when-sigma-is-known" class="section level4 hasAnchor" number="5.3.1.1">
<h4><span class="header-section-number">5.3.1.1</span> When <span class="math inline">\(\sigma\)</span> is Known<a href="confidence-intervals.html#when-sigma-is-known" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>When we know the population standard deviation <span class="math inline">\(\sigma\)</span>, we can
construct a confidence interval for <span class="math inline">\(\mu\)</span> in the following manner.</p>
<p>A <span class="math inline">\((100 - \alpha)\%\)</span> confidence interval on <span class="math inline">\(\mu\)</span> when <span class="math inline">\(\sigma\)</span> is
known is given by
<span class="math display">\[\bar{x} \; \pm \; z_{\alpha/2} \left( \frac{\sigma}{\sqrt{n}} \right)\]</span></p>
<p>The <span class="math inline">\(z_{\alpha/2}\)</span> value is obtained from standard normal tables. The
standard error is <span class="math inline">\(\frac{\sigma}{\sqrt{n}}\)</span> and the margin of error is
<span class="math inline">\(z_{\alpha/2} \left( \frac{\sigma}{\sqrt{n}} \right)\)</span>.<br />
</p>
<p>The critical value <span class="math inline">\(z_{\ast}\)</span> is illustrated in a Figure below and
depends on <span class="math inline">\(C\)</span>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-9"></span>
<img src="Book_Files/figure-html/unnamed-chunk-9-1.png" alt="The central area under the standard normal curve with confidence level \(C\)" width="672" />
<p class="caption">
Figure 5.2: The central area under the standard normal curve with confidence level <span class="math inline">\(C\)</span>
</p>
</div>
<p>$## Table of Common <span class="math inline">\(z\)</span>-values {#table-of-common-z-values .unlisted .unnumbered}
::: {.centered }
Confidence coefficient Confidence level <span class="math inline">\(z\)</span>
———————— —————— ——-
0.90 90% 1.645
0.95 95% 1.96
0.99 99% 2.576
:::</p>
<div class="example">
<p><span id="exm:unlabeled-div-30" class="example"><strong>Example 5.2  </strong></span>Playbill magazine reported that the mean annual household income of its
readers is $119,155. Assume this estimate is based on a sample of 80
households, and that the population standard deviation is known to be
<span class="math inline">\(\sigma = 30{,}000\)</span>.</p>
<ul>
<li><p><span class="math inline">\(\bar{x} = 119{,}155\)</span></p></li>
<li><p><span class="math inline">\(n = 80\)</span></p></li>
<li><p><span class="math inline">\(\sigma = 30{,}000\)</span></p></li>
</ul>
<p><strong>Tasks:</strong></p>
<ol style="list-style-type: decimal">
<li><p>Develop a 90% confidence interval estimate of the population mean.</p></li>
<li><p>Develop a 95% confidence interval estimate of the population mean.</p></li>
<li><p>Develop a 99% confidence interval estimate of the population mean.</p></li>
</ol>
<p><strong>90% CI Calculation</strong></p>
<p><span class="math display">\[\bar{x} \pm z_{\alpha/2} \cdot \frac{\sigma}{\sqrt{n}} = 119{,}155 \pm 1.645 \cdot \frac{30{,}000}{\sqrt{80}}\]</span>
<span class="math display">\[= 119{,}155 \pm 5{,}500.73\]</span> <span class="math display">\[= (113{,}654.27, \; 124{,}655.73)\]</span></p>
<p><strong>95% CI Calculation</strong></p>
<p><span class="math display">\[\bar{x} \pm z_{\alpha/2} \cdot \frac{\sigma}{\sqrt{n}} = 119{,}155 \pm 1.96 \cdot \frac{30{,}000}{\sqrt{80}}\]</span>
<span class="math display">\[= 119{,}155 \pm 6{,}574.04\]</span> <span class="math display">\[= (112{,}580.96, \; 125{,}729.04)\]</span></p>
<p><strong>99% CI Calculation</strong></p>
<p><span class="math display">\[\bar{x} \pm z_{\alpha/2} \cdot \frac{\sigma}{\sqrt{n}} = 119{,}155 \pm 2.576 \cdot \frac{30{,}000}{\sqrt{80}}\]</span>
<span class="math display">\[= 119{,}155 \pm 8{,}620.04\]</span> <span class="math display">\[= (110{,}534.96, \; 127{,}775.04)\]</span></p>
<p><strong>Interpretation</strong></p>
<p>We are 99% confident the mean household income of magazine readers is
between $110,534.96 and $127,775.04.</p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-31" class="example"><strong>Example 5.3  </strong></span><strong>Scenario:</strong></p>
<p>The number of cars sold annually by used car salespeople is known to be
<strong>normally distributed</strong>, with a population standard deviation of
<span class="math inline">\(\sigma = 15\)</span>. A random sample of <span class="math inline">\(n = 15\)</span> salespeople was taken, and
the number of cars each sold is recorded below. Construct a <strong>95%
confidence interval</strong> for the population mean number of cars sold, and
provide an interpretation.</p>
<p><strong>Raw data:</strong></p>
<p><span class="math display">\[\begin{matrix}
79 &amp; 43 &amp; 58 &amp; 66 &amp; 101 \\
63 &amp; 79 &amp; 33 &amp; 58 &amp; 71 \\
60 &amp; 101 &amp; 74 &amp; 55 &amp; 88 \\
\end{matrix}\]</span></p>
<p>The sample mean is:</p>
<p><span class="math display">\[\bar{x} = \frac{79 + 43 + \cdots + 55 + 88}{15} = 68.6\]</span></p>
<p><strong>R function:</strong></p>
<div class="tcolorbox">
<pre><code>simple.z.test = function(x, sigma, conf.level = 0.95) {
  n = length(x);
  xbar = mean(x);
  alpha = 1 - conf.level;
  zstar = qnorm(1 - alpha/2);
  SE = sigma / sqrt(n);
  xbar + c(-zstar * SE, zstar * SE);
}</code></pre>
</div>
<p><strong>R output:</strong></p>
<div class="tcolorbox">
<pre><code># Step 1. Entering data;
cars = c(79, 43, 58, 66, 101, 63, 79,
         33, 58, 71, 60, 101, 74, 55, 88)

# Step 2. Finding CI;
simple.z.test(cars, 15)

## [1] 61.00909 76.19091</code></pre>
</div>
<p><strong>Interpretation:</strong> <strong>We estimate that the mean number of cars sold
annually by all used car salespeople lies between 61 and 76,
approximately. This type of estimate is correct 95% of the time.</strong></p>
</div>
<div class="tcolorbox">
<ul>
<li><p>Large samples where population is <strong>normal</strong>.</p></li>
<li><p>Large samples where population is <strong>not normal</strong> (By CLT).</p></li>
<li><p>Small samples where population is <strong>normal</strong>.</p></li>
</ul>
<p><em>Note: A sample is considered large if <span class="math inline">\(n \geq 30\)</span>.</em></p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-32" class="example"><strong>Example 5.4  </strong></span>Suppose a student measuring the boiling temperature of a certain liquid
observes the readings (in degrees Celsius) 102.5, 101.7, 103.1, 100.9,
100.5, and 102.2 on 6 different samples of the liquid. He calculates the
sample mean to be 101.82. If he knows that the distribution of boiling
points is Normal, with standard deviation 1.2 degrees, what is the
confidence interval for the population mean at a 95% confidence level?<br />
</p>
</div>
<p><strong>A confidence interval</strong> uses sample data to estimate an unknown
population parameter with an indication of how accurate the estimate is
and of how confident we are that the result is correct.</p>
<p>The <strong>interval</strong> often has the form<br />
estimate <span class="math inline">\(\pm\)</span> margin of error</p>
<p>The <strong>confidence level</strong> is the success rate of the method that produces
the interval. A level <span class="math inline">\(C\)</span> <strong>confidence interval for the mean</strong> <span class="math inline">\(\mu\)</span> of
a Normal population with <strong>known</strong> standard deviation <span class="math inline">\(\sigma\)</span>, based on
an SRS of size <span class="math inline">\(n\)</span>, is given by
<span class="math display">\[\bar{x} \pm z^\star \frac{\sigma}{\sqrt{n}}\]</span></p>
<p>The <strong>critical value</strong> <span class="math inline">\(z^\star\)</span> is chosen so that the standard Normal
curve has area <span class="math inline">\(C\)</span> between <span class="math inline">\(-z^\star\)</span> and <span class="math inline">\(z^\star\)</span>.<br />
Other things being equal, the <strong>margin of error</strong> of a confidence
interval gets smaller as</p>
<ul>
<li><p>the confidence level <span class="math inline">\(C\)</span> decreases,</p></li>
<li><p>the population standard deviation <span class="math inline">\(\sigma\)</span> decreases, and</p></li>
<li><p>the sample size <span class="math inline">\(n\)</span> increases.</p></li>
</ul>
<!-- ########## ########## ########## -->
<!-- ########## ########## ########## -->
<!-- ########## ########## ########## -->
</div>
<div id="when-sigma-is-not-known" class="section level4 hasAnchor" number="5.3.1.2">
<h4><span class="header-section-number">5.3.1.2</span> When <span class="math inline">\(\sigma\)</span> is Not known<a href="confidence-intervals.html#when-sigma-is-not-known" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="definition">
<p><span id="def:unlabeled-div-33" class="definition"><strong>Definition 5.3  </strong></span>Let <span class="math inline">\(\mu\)</span> be the population mean. When the population standard deviation
is unknown and the sample size is small, a confidence interval for <span class="math inline">\(\mu\)</span>
is given by:
<span class="math display">\[\bar{Y} \pm t_{\alpha/2} \left( \frac{S}{\sqrt{n}} \right), \quad \nu = n - 1\]</span>
This interval is valid under the following conditions:</p>
<ul>
<li><p>The observations are independent and identically distributed (i.i.d).</p></li>
<li><p>The sample is random.</p></li>
<li><p>The population <strong>must</strong> follow a Normal distribution (CLT does not
apply).</p></li>
</ul>
</div>
</div>
</div>
<div id="independence-assumption" class="section level3 unlisted unnumbered hasAnchor">
<h3>Independence Assumption<a href="confidence-intervals.html#independence-assumption" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The data values should be independent. There’s really no way to check
independence of the data by looking at the sample, but we should think
about whether the assumption is reasonable.</p>
</div>
<div id="randomization-condition" class="section level3 unlisted unnumbered hasAnchor">
<h3>Randomization Condition<a href="confidence-intervals.html#randomization-condition" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The data arise from a random sample or suitably randomized experiment.
Randomly sampled data — especially data from a Simple Random Sample
— are ideal.</p>
<div class="tcolorbox">
<ul>
<li><p>For very small samples (<span class="math inline">\(n &lt; 15\)</span> or so), the data should follow a
Normal model pretty closely. If you do find outliers or strong
skewness, don’t use this method.</p></li>
<li><p>For moderate samples (<span class="math inline">\(n\)</span> between 15 and 40 or so), the t-method will
work well as long as the data is unimodal and reasonably symmetric.
Make a histogram, boxplot, or Q–Q plot to check.</p></li>
<li><p>When the sample size is larger than 40 or 50, the t-method is safe to
use unless the data are extremely skewed. Make a histogram, boxplot,
or Q–Q plot to check.</p></li>
</ul>
</div>
</div>
<div id="standard-error" class="section level3 unlisted unnumbered hasAnchor">
<h3>Standard Error<a href="confidence-intervals.html#standard-error" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When the standard deviation of a statistic is estimated from data, the
result is called the <em>standard error</em> of the statistic. The standard
error of the sample mean <span class="math inline">\(\bar{x}\)</span> is <span class="math display">\[\frac{s}{\sqrt{n}}.\]</span></p>
<div class="tcolorbox">
<ul>
<li><p>The density curves of the <em>t</em> distributions are similar in shape to
the Standard Normal curve. They are symmetric about 0, single-peaked,
and bell-shaped.</p></li>
<li><p>The spread of the <em>t</em> distributions is a bit greater than that of the
Standard Normal distribution. The <em>t</em> distributions have more
probability in the tails and less in the center than the Standard
Normal. This is because substituting the estimate <span class="math inline">\(s\)</span> for the fixed
parameter <span class="math inline">\(\sigma\)</span> introduces more variation into the statistic.</p></li>
<li><p>As the degrees of freedom increase, the <em>t</em> density curve approaches
the <span class="math inline">\(N(0, 1)\)</span> curve more closely. This happens because <span class="math inline">\(s\)</span> estimates
<span class="math inline">\(\sigma\)</span> more accurately as the sample size increases. So using <span class="math inline">\(s\)</span> in
place of <span class="math inline">\(\sigma\)</span> causes little extra variation when the sample is
large.</p></li>
</ul>
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-10"></span>
<img src="Book_Files/figure-html/unnamed-chunk-10-1.png" alt="Comparison of the standard normal distribution and t-distributions with 2 and 9 degrees of freedom" width="672" />
<p class="caption">
Figure 5.3: Comparison of the standard normal distribution and t-distributions with 2 and 9 degrees of freedom
</p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-34" class="example"><strong>Example 5.5  </strong></span>The composition of the Earth’s atmosphere may have changed over time. To
study the nature of the atmosphere long ago, scientists examined the gas
in air bubbles trapped in ancient amber. Amber is fossilized tree resin
that preserved the atmospheric gases at the time it was formed.</p>
<p>Measurements on amber specimens from the late Cretaceous era (75 to 95
million years ago) give the following percent values of nitrogen:</p>
<div class="center">
<p>63.4, 65.0, 64.4, 63.3, 54.8, 64.5, 60.8, 49.1, 51.0</p>
</div>
<p>Assume these observations are a simple random sample (SRS) from the
population of all ancient air bubbles. Construct a <strong>90% confidence
interval</strong> to estimate the mean percent of nitrogen in ancient air.
(Today’s atmosphere contains about 78.1% nitrogen.)</p>
<p><strong>Solution:</strong></p>
<p>Let <span class="math inline">\(\mu\)</span> represent the true mean percent of nitrogen in ancient air. We
compute a 90% confidence interval for <span class="math inline">\(\mu\)</span> using the sample data.</p>
<p>Given:
<span class="math display">\[\bar{x} = 59.5888, \quad s = 6.2552, \quad n = 9, \quad t^* = 1.860 \quad (\text{df} = 8)\]</span></p>
<p><span class="math display">\[59.5888 \pm 1.860 \left( \frac{6.2552}{\sqrt{9}} \right) = 59.5888 \pm 3.8782\]</span></p>
<p><span class="math display">\[\boxed{55.7106 \text{ to } 63.4670}\]</span></p>
<p><strong>R code:</strong></p>
<div class="tcolorbox">
<pre><code># Step 1: Entering the data
nitrogen &lt;- c(63.4, 65.0, 64.4, 63.3, 54.8, 64.5, 60.8, 49.1, 51.0)

# Step 2: Constructing the 90% confidence interval
t.test(nitrogen, conf.level = 0.90)</code></pre>
</div>
<p><strong>R output:</strong></p>
<div class="tcolorbox">
<pre><code>One Sample t-test

data:  nitrogen
t = 28.578, df = 8, p-value = 2.43e-09
alternative hypothesis: true mean is not equal to 0
90 percent confidence interval:
 55.71155 63.46622
sample estimates:
mean of x 
  59.58889 </code></pre>
</div>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-35" class="example"><strong>Example 5.6  </strong></span>Most owners of digital cameras store their pictures on the camera. Some
will eventually download these to a computer or print them using their
own printers or a commercial printer. A film-processing company wanted
to know how many pictures were stored on cameras.</p>
<p>A random sample of 10 digital camera owners produced the following data:</p>
<div class="center">
<p>25, 6, 22, 26, 31, 18, 13, 20, 14, 2</p>
</div>
<p>Estimate with <strong>95% confidence</strong> the mean number of pictures stored on
digital cameras.</p>
<hr />
<p><strong>Solution:</strong></p>
<p>We are given raw data with <span class="math inline">\(n = 10\)</span> and no information about the
population standard deviation, so we construct a confidence interval for
the population mean using the t-distribution.</p>
<p><strong>Step 1: Compute sample statistics</strong></p>
<ul>
<li><p>Sample mean: <span class="math inline">\(\bar{x} = \dfrac{177}{10} = 17.7\)</span></p></li>
<li><p>Sample variance (method 1 – direct):
<span class="math display">\[s^2 = \dfrac{\sum (x_i - \bar{x})^2}{n - 1} = \dfrac{742}{9} = 82.4556\]</span></p></li>
<li><p>Sample standard deviation: <span class="math display">\[s = \sqrt{82.4556} = 9.081\]</span></p></li>
</ul>
<p><strong>Step 2: Find the critical value</strong></p>
<p>For a 95% confidence interval with <span class="math inline">\(n = 10\)</span>, degrees of freedom = 9.
From the t-distribution table: <span class="math display">\[t_{(9, 0.025)} = 2.262\]</span></p>
<p><strong>Step 3: Construct the confidence interval</strong></p>
<p><span class="math display">\[\bar{x} \pm t^* \cdot \dfrac{s}{\sqrt{n}} = 17.7 \pm 2.262 \cdot \dfrac{9.081}{\sqrt{10}} = 17.7 \pm 6.495\]</span></p>
<p><span class="math display">\[\boxed{11.205 \text{ to } 24.195}\]</span></p>
<p><strong>Interpretation:</strong></p>
<p>We are 95% confident that the mean number of images stored on digital
cameras is between 11.205 and 24.195.</p>
<hr />
<p><strong>R code:</strong></p>
<div class="tcolorbox">
<pre><code># Step 1: Entering data
dataset &lt;- c(25, 6, 22, 26, 31, 18, 13, 20, 14, 2)

# Step 2: Finding 95% confidence interval
t.test(dataset, conf.level = 0.95)</code></pre>
</div>
<p><strong>R output:</strong></p>
<div class="tcolorbox">
<pre><code>One Sample t-test

data:  dataset
t = 6.164, df = 9, p-value = 0.0001659
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 11.2042 24.1958
sample estimates:
mean of x 
     17.7 </code></pre>
</div>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-36" class="example"><strong>Example 5.7  </strong></span>A manufacturing company produces electric insulators. If the insulators
break when in use, a short circuit is likely. To test the strength of
the insulators, destructive testing is performed to determine how much
force (in pounds) is required to break them.</p>
<p>The following dataset consists of force values (in pounds) recorded for
a random sample of 30 insulators:</p>
<div class="center">
<p>1870, 1728, 1656, 1610, 1634, 1784, 1522, 1696, 1592, 1662, 1866, 1764,
1734, 1662, 1734, 1774, 1550, 1756, 1762, 1866, 1820, 1744, 1788, 1688,
1810, 1752, 1680, 1810, 1652, 1736</p>
</div>
<p>Construct a <strong>95% confidence interval</strong> for the population mean force
required to break the insulators.</p>
<p><strong>Solution:</strong></p>
<p>We want a confidence interval for the population mean <span class="math inline">\(\mu\)</span>, where
<span class="math inline">\(\mu =\)</span> mean force required to break electric insulators. The population
standard deviation is unknown, so we use a <em>one-sample</em> t-interval.</p>
<p><strong>R code:</strong></p>
<div class="tcolorbox">
<pre><code># Step 1. Entering data;
dataset &lt;- c(1870, 1728, 1656, 1610, 1634, 1784, 1522, 1696, 1592, 1662,
             1866, 1764, 1734, 1662, 1734, 1774, 1550, 1756, 1762, 1866,
             1820, 1744, 1788, 1688, 1810, 1752, 1680, 1810, 1652, 1736)

# Step 2. Finding CI;
t.test(dataset, conf.level = 0.95)</code></pre>
</div>
<p><strong>R output:</strong></p>
<div class="tcolorbox">
<pre><code>One Sample t-test

data:  dataset
t = 105.41, df = 29, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 1689.961 1756.839
sample estimates:
mean of x 
   1723.4 </code></pre>
</div>
<p><strong>Interpretation:</strong></p>
<p>We are 95% confident that the average force required to break an
electric insulator is between <strong>1689.961 pounds</strong> and <strong>1756.839
pounds</strong>.</p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-37" class="example"><strong>Example 5.8  </strong></span>The operations manager of a production plant would like to estimate the
mean amount of time a worker takes to assemble a new electronic
component. After observing 120 workers assembling similar devices, she
noticed that their average time was 16.2 minutes (with a standard
deviation of 3.6 minutes).</p>
<p>Construct a <strong>92% confidence interval</strong> for the mean assembly time.
State all necessary assumptions.</p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-38" class="example"><strong>Example 5.9  </strong></span>In 2010, 142,823,000 tax returns were filed in the United States. The
Internal Revenue Service (IRS) examined 1.107%, or 1,581,000, of them to
determine if they were correctly done. To evaluate auditor performance,
a random sample of these returns was drawn and the additional tax was
recorded.</p>
<p>Estimate with 95% confidence the mean additional income tax collected
from the 1,581,000 files audited.<br />
<strong>Solution:</strong></p>
<p>We use a one-sample confidence interval for the population mean
additional tax collected.</p>
<p><strong>Step 1: Import the data from <code>taxes.txt</code></strong></p>
<div class="tcolorbox">
<pre><code># url of taxes;
url &lt;- &quot;https://mcs.utm.utoronto.ca/~nosedal/data/taxes.txt&quot;
taxes_data &lt;- read.table(url, header = TRUE)

# inspect structure
names(taxes_data)
head(taxes_data)

# isolate the tax values
taxes &lt;- taxes_data$Taxes</code></pre>
</div>
<p><strong>Step 2: Plot the data</strong></p>
<p><em>Histogram:</em></p>
<div class="tcolorbox">
<pre><code>hist(taxes,
     main = &quot;Histogram for our example&quot;,
     xlab = &quot;taxes&quot;, ylab = &quot;frequency&quot;,
     col = &quot;blue&quot;)</code></pre>
</div>
<div class="center">
<div class="figure" style="text-align: center">
<img src="Book_Files/figure-html/unnamed-chunk-11-1.png" alt=" " width="672" />
<p class="caption">
</p>
</div>
</div>
<p><em>Boxplot:</em></p>
<div class="tcolorbox">
<pre><code>boxplot(taxes,
        main = &quot;Additional Income Tax&quot;,
        col = &quot;blue&quot;)</code></pre>
</div>
<div class="center">
<div class="figure" style="text-align: center">
<img src="Book_Files/figure-html/unnamed-chunk-12-1.png" alt=" " width="672" />
<p class="caption">
</p>
</div>
</div>
<p><em>Q-Q Plot:</em></p>
<div class="tcolorbox">
<pre><code>qqnorm(taxes, col = &quot;blue&quot;, pch = 19)
qqline(taxes)</code></pre>
</div>
<div class="center">
<div class="figure" style="text-align: center">
<img src="Book_Files/figure-html/unnamed-chunk-13-1.png" alt=" " width="672" />
<p class="caption">
</p>
</div>
</div>
<p><strong>Step 3: Construct 95% CI</strong></p>
<div class="tcolorbox">
<pre><code>t.test(taxes, conf.level = 0.95)</code></pre>
</div>
<p><strong>Interpretation:</strong> Based on the t-test, we are 95% confident that the
average additional tax collected lies within the interval calculated
from the sample.</p>
<p><strong>Assumptions:</strong></p>
<ul>
<li><p>The sample is a random sample from the population of interest.</p></li>
<li><p>Observations are independent.</p></li>
<li><p>The population is approximately Normal, or the sample size is large
enough (justified by the histogram, boxplot, and Q-Q plot).</p></li>
</ul>
<div class="tcolorbox">
<pre><code>## 
##  One Sample t-test
## 
##  data:  taxes
##  t = 29.345, df = 191, p-value &lt; 2.2e-16
##  alternative hypothesis: true mean is not equal to 0
##  95 percent confidence interval:
##   8886.932 10167.721
##  sample estimates:
##  mean of x 
##    9527.326 </code></pre>
</div>
<p><strong>Interpretation:</strong></p>
<p>We estimate that the mean additional tax collected lies between $8,887
and $10,168 (with 95% confidence).</p>
</div>
</div>
<div id="a-few-final-comments" class="section level3 unlisted unnumbered hasAnchor">
<h3>A few final comments<a href="confidence-intervals.html#a-few-final-comments" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When we introduced the Student <em>t</em>-distribution, we pointed out that the
<em>t</em>-statistic is Student <em>t</em>-distributed if the population from which
we’ve sampled is Normal. However, statisticians have shown that the
mathematical process that derived the Student <em>t</em>-distribution is
<strong>robust</strong>, which means that if the population is non-Normal, the
results of the confidence interval estimate are still valid provided
that the population is <strong>not extremely non-Normal</strong>. Our histogram,
boxplot, and Q–Q plot suggest that our variable of interest is not
extremely non-Normal, and in fact, may be Normal.</p>
<!-- ########## ########## ########## -->
<!-- ########## ########## ########## -->
<!-- ########## ########## ########## -->
</div>
<div id="on-a-population-proportion" class="section level3 hasAnchor" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> On a Population Proportion<a href="confidence-intervals.html#on-a-population-proportion" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Previously, we have introduced two types of confidence interval based on
known and unknown variance. Moreover, confidence intervals are also
applied to an unknown population proportion. For example, suppose we are
interested the proportion of total number of left-handed students among
all students who are currently studying at University of Toronto
Mississauga. The question is: how do we know such the parameter which
estimates the proportion of left-handed students at UTM? While, it is
impossible to proceed it directly by counting both the total number of
students and all left-handed students at UTM, due to the complexity and
the total workload of that task. Then, we have to work with confidence
intervals.</p>
<p>First, we take a random sample of students at UTM, then we calculate
how many students are left-handed by dividing total number of
left-handed students in that sample with total number of students in it,
and denote the proportion as <span class="math inline">\(\hat{p}\)</span>. Next we begin our confidence
interval calculation to get a range of number with a certain level of
confidence.</p>
<p>Now let’s begin with the proper definition of confidence interval on
proportion.</p>
<div class="definition">
<p><span id="def:unlabeled-div-39" class="definition"><strong>Definition 5.4  </strong></span>We select a random sample of size <span class="math inline">\(n\)</span> from a population with <strong>unknown</strong>
proportion <span class="math inline">\(p\)</span> of success. An approximate confidence interval for <strong>p</strong>
is:
<span class="math display">\[p = \hat{p}  \pm z_{\frac{\alpha}{2}} \cdot \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}}, \text{ where $\hat{p} = \frac{\text{number of observations satisfying the criteria}}{n}$.}\]</span>
In addition, <span class="math inline">\(n\)</span> is the sample size.<br />
To apply this confidence interval, there are <span class="math inline">\(3\)</span> conditions that we need
to guarantee:</p>
<ul>
<li><p><span class="math inline">\(1\)</span>. Random sample;</p></li>
<li><p><span class="math inline">\(2\)</span>. Independent and identically distributed Bernoulli trails;</p></li>
<li><p><span class="math inline">\(3\)</span>. We have a large chosen sample size (<span class="math inline">\(n\hat{p} \ge 10\)</span> and
<span class="math inline">\(n(1-\hat{p}) \ge 10\)</span>).</p></li>
</ul>
</div>
<p>A good way to understand confidence interval is visualization. Now,
suppose we have a valid estimation <span class="math inline">\(\hat{p}\)</span>. After the entire procedure
of confidence interval, our population proportion (<span class="math inline">\(p\)</span>) should be as the
following number line shows:<br />
</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-14"></span>
<img src="Book_Files/figure-html/unnamed-chunk-14-1.png" alt="Visualization of the result of confidence interval on a proportion." width="90%" />
<p class="caption">
Figure 5.4: Visualization of the result of confidence interval on a proportion.
</p>
</div>
<p>Remember that your final answer of the range of <span class="math inline">\(p\)</span> must between <span class="math inline">\(0\)</span> and
<span class="math inline">\(1\)</span>, since we are working with proportion.</p>
<p><strong>Summary about One Sample Confidence Intervals</strong></p>
<p>We have introduced one sample confidence interval under three different
cases: given population variance, unknown population variance and
unknown population proportion. All the material of one sample confidence
interval comes from chapter <span class="math inline">\(6, 7, 8\)</span>, which seems like you to remember
a lot. However, the reason why we give this summery is to help you to
remember the basic skeleton of one sample confidence interval. Let’s
revisit the three distinct types of confidence interval:</p>
<ul>
<li><p>Known variance:
<span class="math inline">\(\hat{x} \pm z_{\alpha/2} \cdot \frac{\sigma}{\sqrt{n}}\)</span> <a href="#ch:7">(Chapter
7)</a>.</p></li>
<li><p>Unknown variance:
<span class="math inline">\(\bar{x} \pm t_{\scriptscriptstyle{\alpha/2}} \cdot \frac{s}{\sqrt{n}}\)</span></p></li>
<li><p>Proportion:
<span class="math inline">\(\hat{p} \pm z_{\scriptscriptstyle{\alpha/2}} \cdot \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\)</span></p></li>
</ul>
<p>The question is: what is the similarity between the three distinct types
of confidence interval? You may have already noticed that the confidence
intervals above are all follow such a skeleton that <span class="math inline">\(\bar{x}\)</span> plus or
minus its margin of error (different between each type of C.I.).<br />
If we keep questioning ourselves that how the margin of error comes
from, you will catch the pattern. The margin of error contains reference
distribution and the standard deviation of <span class="math inline">\(\bar{x}\)</span> under its reference
distribution. Let’s analyze each type of confidence interval to prove my
statement is true:<br />
The first type (given population variance) confidence interval is quite
easy to recognize. Recall chapter <span class="math inline">\(3\)</span>: The Central Limit Theorem, we
state that <span class="math inline">\(\bar{x} \sim N(\mu, \frac{\sigma^2}{n})\)</span>, which is how
reference distribution comes from with given population variance. To get
the standard deviation of <span class="math inline">\(\bar{x}\)</span>, we simply take the square root of
the variance, then <span class="math inline">\(s_{\bar{x}} = \frac{\sigma}{\sqrt{n}}\)</span>. Finally, we
multiply reference distribution at the point <span class="math inline">\(\frac{\alpha}{2}\)</span> with the
standard deviation of <span class="math inline">\(\bar{x}\)</span> under normal distribution to get the
margin of error.<br />
The second type (unknown population variance) confidence interval is
similar to the first type, but the reference distribution is
t-distribution instead of normal distribution. In chapter <span class="math inline">\(7\)</span>, we
introduced the calculation of sample variance (<span class="math inline">\(s^2\)</span>) to estimate
population variance (<span class="math inline">\(\sigma^2\)</span>), and <span class="math inline">\(s^2\)</span> is an unbiased estimator of
<span class="math inline">\(\sigma^2\)</span> (the proof of this statement is in STA260, in this course we
can assume it freely). In chapter <span class="math inline">\(2\)</span>, we defined that
<span class="math inline">\(T = \frac{\bar{x} - \mu}{(\frac{s}{\sqrt{n}})} \sim t_{n-1},\)</span> then the
term <span class="math inline">\(\frac{s}{\sqrt{n}}\)</span> (verify this by yourself as an extra exercise)
is the standard deviation of <span class="math inline">\(\bar{x}\)</span> under t-distribution with <span class="math inline">\(n-1\)</span>
degrees of freedom. Finally, we multiply multiply reference distribution
at the point <span class="math inline">\(\frac{\alpha}{2}\)</span> with the standard deviation of <span class="math inline">\(\bar{x}\)</span>
under t-distribution to get the margin of error.<br />
The third type (estimate population proportion) confidence interval is
slightly harder to identify. Recall chapter <span class="math inline">\(4\)</span> that we can approximate
binomial distribution by normal distribution. Suppose that a random
variable <span class="math inline">\(X \sim Binomial(n,p)\)</span>, then the random variable
<span class="math inline">\(X \sim N(np, np(1-p)).\)</span> From chapter <span class="math inline">\(4\)</span>, we know that
<span class="math inline">\(\hat{p} \sim N(\mu_{\hat{p}} = p, \sigma_{\hat{p}}^{2} = \frac{p(1-p)}{n})\)</span>.
Trivially, the standard deviation of <span class="math inline">\(\hat{p}\)</span> is
<span class="math inline">\(\sqrt{\frac{p(1-p)}{n}}\)</span>, since we don’t know the value <span class="math inline">\(p\)</span> and use
<span class="math inline">\(\hat{p}\)</span> to estimate that. Then, standard deviation of <span class="math inline">\(\hat{p}\)</span> is
<span class="math inline">\(\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\)</span>. Finally, by multiplying the
reference distribution and standard deviation, we get the margin of
error of the confidence interval.<br />
<strong>Conclusion About One Sample Confidence Intervals</strong></p>
<p>If you follow the skeleton below, one sample confidence interval will
become easier:</p>
<ul>
<li><p>1. Identify what type of one sample confidence interval to use from
given information;</p></li>
<li><p>2. Construct your confidence interval that fits the circumstance
which you are facing, it either going to be
<span class="math inline">\(\bar{x}  \pm M.E.(\bar{x})\text{ or } \hat{p}  \pm M.E.(\hat{p});\)</span></p></li>
<li><p>3. Check the validity of your final answer. For example, the range of
<span class="math inline">\(p\)</span> must between <span class="math inline">\(0\)</span> and <span class="math inline">\(1\)</span>.</p></li>
<li><p>4. Clearly state your final conclusion: we have a certain percentage
of confidence to guarantee that the value of the chosen sample is
between its lower bound and upper bound.</p></li>
</ul>
<!-- ########## ########## ########## -->
<!-- ########## ########## ########## -->
<!-- ########## ########## ########## -->
</div>
<div id="on-a-population-variance" class="section level3 hasAnchor" number="5.3.3">
<h3><span class="header-section-number">5.3.3</span> On a Population Variance<a href="confidence-intervals.html#on-a-population-variance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>** Needs to be completed **</p>
</div>
<div id="assumptions" class="section level3 hasAnchor" number="5.3.4">
<h3><span class="header-section-number">5.3.4</span> Assumptions<a href="confidence-intervals.html#assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>** Needs to be completed **</p>
<!-- ########## ########## ########## -->
<!-- ########## ########## ########## -->
<!-- ########## ########## ########## -->
<!-- ########## ########## ########## -->
<!-- ########## ########## ########## -->
<!-- ########## ########## ########## -->
</div>
</div>
<div id="two-sample-confidence-intervals" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Two Sample Confidence Intervals<a href="confidence-intervals.html#two-sample-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We have discussed three distinct types of one sample confidence
interval. Now, let’s keep moving forward to see how confidence interval
works for two sample. The aim of one sample confidence interval is
giving a range of numbers to estimate population mean or proportion with
a certain percentage of confidence. For two samples, the aim is
comparing with sample has a relatively larger or smaller population mean
or proportion with a certain percentage of confidence.</p>
<div id="on-a-difference-of-means" class="section level3 hasAnchor" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> On a Difference of Means<a href="confidence-intervals.html#on-a-difference-of-means" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose we are interested in the final mark of MAT135 from the same
semester but with different campuses at the University of Toronto (let’s
use UTSG and UTM as the two independent population groups). We want to
know which campus has a relatively higher average score, the question
is: how do we determine that? It is going to be complicated if we
proceed with the study directly by determining the sum of everyone’s
final marks and calculating the average for the two campuses. Similarly,
as one sample confidence interval, we can select two groups of random
sample from the two campuses (one group per each campus), and then
calculate each sample mean. Finally, we apply a confidence interval to
approximate which population has a higher mean (or average).</p>
<p>Similar to one-sample confidence intervals on
a mean, we examine various cases of two-sample confidence intervals on a difference means.</p>
<div id="when-sigma_1-and-sigma_2-are-known" class="section level4 hasAnchor" number="5.4.1.1">
<h4><span class="header-section-number">5.4.1.1</span> When <span class="math inline">\(\sigma_1\)</span> and <span class="math inline">\(\sigma_2\)</span> are Known<a href="confidence-intervals.html#when-sigma_1-and-sigma_2-are-known" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="definition">
<p><span id="def:unlabeled-div-40" class="definition"><strong>Definition 5.5  </strong></span>Suppose we are given the population variance for both two independent
groups of population. The confidence interval of <span class="math inline">\(\mu_1 - \mu_2\)</span>
(difference of mean between population group 1 and 2) is given by the
following:
<span class="math display">\[(\bar{x}_{1} - \bar{x}_{2})  \pm z_{\small\alpha/2} \cdot \sqrt{ \frac{\sigma_1^2}{n_1} + \frac{\sigma_2^2}{n_2}}.\]</span>
For <span class="math inline">\(\sigma_1^2\)</span>, which is population variance of population group 1;
<span class="math inline">\(n_1\)</span> is the sample size chosen form population group 1. Similarly for
<span class="math inline">\(\sigma_2^2\)</span>, which is population variance of population group 2; <span class="math inline">\(n_2\)</span>
is the sample size chosen form population group 2.</p>
</div>
<p>This situation is a bit unrealistic with other cases because the
population variance (<span class="math inline">\(\sigma^2\)</span>) from both groups are rare to know.</p>
<!-- ########## ########## ########## -->
</div>
<div id="when-sigma_1-and-sigma_2-are-not-known" class="section level4 hasAnchor" number="5.4.1.2">
<h4><span class="header-section-number">5.4.1.2</span> When <span class="math inline">\(\sigma_1\)</span> and <span class="math inline">\(\sigma_2\)</span> are Not Known<a href="confidence-intervals.html#when-sigma_1-and-sigma_2-are-not-known" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In practice, we usually do not have the information about population variance.
The situations in this section are a lot more realistic.
In the case when the variances of both populations are unknown,
we consider two subcases.</p>
<!-- ########## ########## ########## -->
</div>
<div id="when-sigma_1-sigma_2" class="section level4 hasAnchor" number="5.4.1.3">
<h4><span class="header-section-number">5.4.1.3</span> When <span class="math inline">\(\sigma_1 = \sigma_2\)</span><a href="confidence-intervals.html#when-sigma_1-sigma_2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We first examine the case where we assume the standard deviation of both populations is assumed equal.</p>
<div class="definition">
<p><span id="def:unlabeled-div-41" class="definition"><strong>Definition 5.6  </strong></span>Suppose that the chosen two independent samples have same unknown
population variance. Then the two sample confidence interval for
<span class="math inline">\(\mu_1 - \mu_2\)</span> is given by the following:
<span class="math display">\[(\bar{x}_1 - \bar{x}_2)  \pm  t_{n_1+n_2-2; \alpha/2} \cdot s_p \cdot \sqrt{\frac{1}{n_1} + \frac{1}{n_2}}.\]</span>
In this case, <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> are sample size from the two chosen
samples respectively; <span class="math inline">\(s_p\)</span> is aggregated variance of both samples
combined which accommodates samples of different sizes. Additionally,
<span class="math inline">\(s_p\)</span> is called pooled standard deviation which is calculated by the
following equation:
<span class="math display">\[s_p^2 = \frac{(n_1-1) \cdot s_1^2 + (n_2-1) \cdot s_2^2 }{n_1+n_2-2},\]</span>
where <span class="math inline">\(s_1^2\)</span> and <span class="math inline">\(s_2^2\)</span> are sample variance of the two chosen samples
respectively.<br />
Then we take the square root <span class="math inline">\(s_p = \sqrt{s_p^2}\)</span> to get pooled standard
deviation.</p>
</div>
<p>Alternatively, we can write the equation for two sample confidence
interval with equal unknown variance as:
<span class="math display">\[(\bar{x}_1 - \bar{x}_2)  \pm  t_{n_1+n_2-2; \alpha/2} \cdot \sqrt{s_p^2(\frac{1}{n_1} + \frac{1}{n_2})}, \text{ which is same as the one above.}\]</span></p>
<p>The pooled variance (also known as combined variance,
composite variance, or overall variance) is a method to calculate such a
value in order to estimate variance between several distinct
populations. The mean of each population may or may not be the same, but
the variance of these populations are same. Pooled standard deviation
does similar thing, we use that value to estimate standard deviation
instead of variance.</p>
<!-- ########## ########## ########## -->
</div>
<div id="when-sigma_1-neq-sigma_2" class="section level4 hasAnchor" number="5.4.1.4">
<h4><span class="header-section-number">5.4.1.4</span> When <span class="math inline">\(\sigma_1 \neq \sigma_2\)</span><a href="confidence-intervals.html#when-sigma_1-neq-sigma_2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We now examine the case where we assume the standard deviation of both populations is assumed different.</p>
<div class="definition">
<p><span id="def:unlabeled-div-42" class="definition"><strong>Definition 5.7  </strong></span>Suppose that our chosen two independent samples with unequal and unknown
population variance, then the confidence interval for <span class="math inline">\(\mu_1 - \mu_2\)</span> is
given by:
<span class="math display">\[(\bar{x}_1 - \bar{x}_2)  \pm t_{df; \alpha/2} \cdot \sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}, \text{ where: $df = min(n_1-1, n_2-1)$.}\]</span>
Moreover, <span class="math inline">\(s_1^2\)</span> and <span class="math inline">\(s_2^2\)</span> are sample variance of the two chosen
groups; and <span class="math inline">\(n_1\)</span>, <span class="math inline">\(n_2\)</span> are the sample size of the two chosen groups
respectively.</p>
</div>
</div>
<div id="assumptions-1" class="section level4 hasAnchor" number="5.4.1.5">
<h4><span class="header-section-number">5.4.1.5</span> Assumptions<a href="confidence-intervals.html#assumptions-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Same as all previous confidence intervals, we still need several
conditions that guarantee the validity two sample confidence interval:</p>
<ul>
<li><p>1. The two chosen sample is required to be independent and random;</p></li>
<li><p>2. If both sample size are small (both <span class="math inline">\(n_1 &lt; 30\)</span> and <span class="math inline">\(n_2 &lt; 30\)</span>),
then both sample should be from normal population;</p></li>
<li><p>3. If one of the sample has a small size (either <span class="math inline">\(n_1 &lt; 30\)</span> or
<span class="math inline">\(n_2 &lt; 30\)</span>), then the smaller sample must be from a normal population;</p></li>
</ul>
<p>Note that if both <span class="math inline">\(n_1 \ge 30\)</span> and <span class="math inline">\(n_2 \ge 30\)</span>, then normality
assumption is not required by the Central Limit Theorem.<br />
<strong>Example (Comparing Two Population Means Managerial Success Indexes for
Two Groups)</strong></p>
</div>
</div>
<div id="on-a-difference-of-proportions" class="section level3 hasAnchor" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> On a Difference of Proportions<a href="confidence-intervals.html#on-a-difference-of-proportions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Furthermore, two sample confidence intervals can approximate the
proportion as well. Suppose we are interested in the proportion of
left-handed students in UTSG and UTM, and we are asked to find the
campus that has a relatively larger proportion of left-handed students.
To begin with this task, it is impossible to complete it directly by
calculation, due to its complexity and high workload. We can use select
two independent groups (one group from each campus), then apply two
sample confidence interval to approximate which campus has a larger
proportion.</p>
<div class="definition">
<p><span id="def:unlabeled-div-43" class="definition"><strong>Definition 5.8  </strong></span>Draw an SRS of size <span class="math inline">\(n_1\)</span> from a population having proportion <span class="math inline">\(p_1\)</span> of
successes and draw an independent SRS of size <span class="math inline">\(n_2\)</span> from another
population having proportion <span class="math inline">\(p_2\)</span> of successes. When <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span>
are large, an approximate level C confidence interval for <span class="math inline">\(p_1 - p_2\)</span> is
given by:
<span class="math display">\[(\hat{p}_1 - \hat{p}_2)  \pm z_{\alpha/2} \cdot \sqrt{ \frac{\hat{p}_1(1-\hat{p}_1)}{n_1} + \frac{\hat{p}_2(1-\hat{p}_2)}{n_2}}.\]</span>
Now, <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> are sample size of selected random sample from each
population; <span class="math inline">\(\hat{p}_1\)</span> and <span class="math inline">\(\hat{p}_2\)</span> are the proportion of success of
each selected random sample respectively.</p>
</div>
<div id="assumptions-2" class="section level4 hasAnchor" number="5.4.2.1">
<h4><span class="header-section-number">5.4.2.1</span> Assumptions<a href="confidence-intervals.html#assumptions-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><p>1. Randomization Condition: The data in each group should be drawn
independently and at random from a population or generated b y a
completely randomized designed experiment.</p></li>
<li><p>2. The <span class="math inline">\(10\%\)</span> Condition: If the data are sampled without replacement,
the sample should not exceed <span class="math inline">\(10\%\)</span> of the population. If samples are
bigger than <span class="math inline">\(10\%\)</span> of the target population, random draws are no
longer approximately independent.</p></li>
<li><p>3. Independent Groups Assumption: The two groups we are comparing
must be independent from each other.</p></li>
<li><p>4. Sample size requirement: both selected sample size must greater
than <span class="math inline">\(70\)</span>.</p></li>
</ul>
</div>
</div>
<div id="on-a-ratio-of-variances" class="section level3 hasAnchor" number="5.4.3">
<h3><span class="header-section-number">5.4.3</span> On a Ratio of Variances<a href="confidence-intervals.html#on-a-ratio-of-variances" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Confidence interval is a strong technique in inferential statistics, we
have discussed its application on population mean, proportion and
dependent data. Now, let’s move on to variance.<br />
One simple method involves just looking at two sample variances.
Logically, if two population variances are equal, then the two sample
variances should be very similar. When the two sample variances are
reasonably close, you can be reasonably conﬁdent that the homogeneity
assumption is satisﬁed and proceed with, for example, Student
t-interval. However, when one sample variance is three or four times
larger than the other, then there is reason for a concern. The common
statistical procedure for comparing population variances <span class="math inline">\(\sigma_1^2\)</span>
and <span class="math inline">\(\sigma_2^2\)</span> makes an inference about the ratio of
<span class="math inline">\((\sigma_1^2)/(\sigma_2^2)\)</span>.<br />
To make an inference about the ratio of <span class="math inline">\((\sigma_1^2)/(\sigma_2^2)\)</span> we
collect sample data and use the ratio of the sample variances
<span class="math inline">\((\sigma_1^2)/(\sigma_2^2)\)</span>.</p>
<p>At this point, let’s derive the confidence interval. We know that:
<span class="math inline">\(\frac{s_1^2/\sigma_1^2}{s_2^2/\sigma_2^2} \sim F_{n_1-1, n_2 -1}\)</span>.
Then, we can construct our confidence interval as:
<span class="math display">\[P[F_{n_1-1, n_2 -1; 1-\alpha/2} &lt; \frac{s_1^2/\sigma_1^2}{s_2^2/\sigma_2^2} &lt; F_{n_1-1, n_2 -1; \alpha/2}]  = 1 -\alpha.\]</span>
Now, the reference distribution of this confidence interval is
F-distribution with <span class="math inline">\(n_1 - 1\)</span> and <span class="math inline">\(n_2 -1\)</span> degrees of freedom, leaving
areas of <span class="math inline">\(1 - \alpha/2\)</span> and <span class="math inline">\(\alpha/2\)</span>, respectively, to the right.
Rearranging gives us:
<span class="math display">\[P[\frac{s_1^2}{s_2^2} \cdot \frac{1}{F_{n_1-1, n_2 -1; \alpha/2}} &lt; \frac{\sigma_1^2}{\sigma_2^2} &lt; \frac{s_1^2}{s_2^2} \cdot \frac{1}{F_{n_1-1, n_2 -1; 1-\alpha/2}}] = 1 -\alpha.\]</span>
Using the face that
<span class="math inline">\(F_{n_1-1,n_2-1; 1 - \alpha/2} = \frac{1}{F_{n_2-1,n_1-1; \alpha/2}}\)</span>,
we have:
<span class="math display">\[P[\frac{s_1^2}{s_2^2} \cdot \frac{1}{F_{n_1-1, n_2-1, \alpha/2}} &lt; \frac{\sigma_1^2}{\sigma_2^2} &lt; \frac{s_1^2}{s_2^2} \cdot F_{n_2-1, n_1 - 1, \alpha/2}] = 1- \alpha.\]</span></p>
<div id="assumptions-3" class="section level4 hasAnchor" number="5.4.3.1">
<h4><span class="header-section-number">5.4.3.1</span> Assumptions<a href="confidence-intervals.html#assumptions-3" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><strong>Need to complete</strong></p>
</div>
</div>
</div>
<div id="confidence-intervals-on-paired-data" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> Confidence Intervals on Paired Data<a href="confidence-intervals.html#confidence-intervals-on-paired-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>It may appear that two sample confidence interval only works on two
independent samples, however what about two dependent samples? Suppose
we are interested the growth of height from several distinct elementary
students. We measure their height recently, then we will do it another
time with five years later. The question is: how are we going to proceed
with two confidence interval? While, the answer is yes. We are able to
do so by constructing two sample confidence interval, but with a
different strategy.</p>
<p>We may have situations</p>
<div id="direct" class="smalltbl">
<table>
<colgroup>
<col width="13%" />
<col width="26%" />
<col width="26%" />
<col width="32%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Sample Units</th>
<th align="center">Measurement 1 (<span class="math inline">\(M_{1}\)</span>)</th>
<th align="center">Measurement 2 (<span class="math inline">\(M_{2}\)</span>)</th>
<th align="center">Difference (<span class="math inline">\(M_{2}-M_{1}\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="center"><span class="math inline">\(x_{11}\)</span></td>
<td align="center"><span class="math inline">\(x_{12}\)</span></td>
<td align="center"><span class="math inline">\(x_{d1} = x_{12} - x_{11}\)</span></td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="center"><span class="math inline">\(x_{21}\)</span></td>
<td align="center"><span class="math inline">\(x_{22}\)</span></td>
<td align="center"><span class="math inline">\(x_{d2} = x_{22} - x_{21}\)</span></td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="center"><span class="math inline">\(x_{31}\)</span></td>
<td align="center"><span class="math inline">\(x_{32}\)</span></td>
<td align="center"><span class="math inline">\(x_{d3} = x_{32} - x_{31}\)</span></td>
</tr>
<tr class="even">
<td align="right"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="odd">
<td align="right">n</td>
<td align="center"><span class="math inline">\(x_{n1}\)</span></td>
<td align="center"><span class="math inline">\(x_{n2}\)</span></td>
<td align="center"><span class="math inline">\(x_{dn} = x_{n2} - x_{n1}\)</span></td>
</tr>
</tbody>
</table>
</div>
<!-- |              |                          |                          | $\bar{x}_{d} = \displaystyle\frac{\displaystyle\sum_{i=1}^{m} x_{di}}{n}$ | -->
<!-- |              |                          |                          | $s_{d} = \displaystyle\frac{\displaystyle\sum_{i=1}^{m} (x_{di} - \bar{x}_{d} )^2}{n-1}$ | -->
<p>The table shows how calculate paired data.
In each row, <em>Measurement 1</em>is a measurement on a sample unit
and the <em>Measurement 2</em> is a measurement on the <em>same</em> unit.
We then calculate the difference between the two measurements for each of the measurements for each unit
as shown in the last column,
difference between the second and the first measurement (<span class="math inline">\(M_2 - M_1\)</span>).</p>
<div class="remark">
<p><span id="unlabeled-div-44" class="remark"><em>Remark</em>. </span>In the table above, we calculated differences as <span class="math inline">\(M_{2} - M_{1}\)</span>, however it is also possible to calculate <span class="math inline">\(M_{2} - M_{1}\)</span>.
The final results and interpretation will be the same, however one order in which measurements are subtracted
may be more convenient than the other.</p>
</div>
<p>To calculate the confidence interval on paired data, we first need to calculate the mean and sample variance of the difference data using:</p>
<p><span class="math display">\[\bar{x}_{d} = \displaystyle\frac{\displaystyle\sum_{i=1}^{m} x_{di}}{n},
\quad\quad
s_{d} = \displaystyle\frac{\displaystyle\sum_{i=1}^{m} (x_{di} - \bar{x}_{d} )^2}{n-1}.\]</span></p>
<p>Then we can use the fourth column to get the mean value, sample variance
and sample standard deviation of the difference. Now, let’s begin with
the proper definition:</p>
<div class="definition">
<p><span id="def:unlabeled-div-45" class="definition"><strong>Definition 5.9  </strong></span>Suppose we have two samples that are dependent with each other, the
confidence interval on paired data’s mean (<span class="math inline">\(\mu_d\)</span>) is given by:
<span class="math display">\[\bar{x}_d  \pm t_{n-1, \alpha/2} \cdot \frac{s_d}{\sqrt{n}}.\]</span> In this
case, the reference distribution is t-distribution with <span class="math inline">\(n-1\)</span> degrees of
freedom (sample size minus <span class="math inline">\(1\)</span>), <span class="math inline">\(\bar{x}_d\)</span> represents the sample mean
of difference between the two measurements on the paired data, <span class="math inline">\(s_d\)</span> is
the sample standard deviation of difference between the two
measurements.</p>
</div>
<div id="assumptions-4" class="section level4 hasAnchor" number="5.5.0.1">
<h4><span class="header-section-number">5.5.0.1</span> Assumptions<a href="confidence-intervals.html#assumptions-4" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><strong>Need to complete</strong></p>
<!-- ########## ########## ########## -->
<!-- ########## ########## ########## -->
<!-- ########## ########## ########## -->
</div>
</div>
<div id="sample-size-selection-using-confidence-intervals" class="section level2 hasAnchor" number="5.6">
<h2><span class="header-section-number">5.6</span> Sample Size Selection using Confidence Intervals<a href="confidence-intervals.html#sample-size-selection-using-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section we will examine techniques to calculate the minimum
sample size required to obtain a confidence interval to be within a
specified margin of error.</p>
<div id="secSampleSizeCIMean" class="section level3 hasAnchor" number="5.6.1">
<h3><span class="header-section-number">5.6.1</span> Calculating Sample Size for a Confidence Interval on a Mean<a href="confidence-intervals.html#secSampleSizeCIMean" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will examine how to calculate the minimum sample size <span class="math inline">\(n\)</span> for a
confidence interval on a mean for a margin of error <span class="math inline">\(E\)</span> at confidence
level <span class="math inline">\(1-\alpha\)</span>.</p>
<div id="when-sigma-is-known" class="section level4 unnumbered unlisted hasAnchor">
<h4>When <span class="math inline">\(\sigma\)</span> is Known<a href="confidence-intervals.html#when-sigma-is-known" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>For a desired margin of error <span class="math inline">\(E\)</span> and confidence level <span class="math inline">\(1-\alpha\)</span>:
<span class="math display">\[E = z_{\alpha/2}\,\frac{\sigma}{\sqrt{n}}\]</span></p>
<p>We can rearrange <span class="math inline">\(E\)</span> to calculate the sample size using
<span class="math display">\[n = \left( \frac{z_{\alpha/2}\,\sigma}{E} \right)^2\]</span> where <span class="math inline">\(n\)</span> is
always <em>rounded up</em> to the next integer.<br />
</p>
<div class="example">
<p><span id="exm:SampleSizePharmaceutical" class="example"><strong>Example 5.10  </strong></span>A manufacturer of pharmaceutical products analyzes a specimen from each
batch of a product to verify the concentration of the active ingredient.
The chemical analysis is not perfectly precise. Repeated measurements on
the same specimen give slightly different results. Suppose we know that
the results of repeated measurements follow a Normal distribution with
mean <span class="math inline">\(\mu\)</span> equal to the true concentration and standard deviation
<span class="math inline">\(\sigma = 0.0068\)</span> grams per liter. (That the mean of the population of
all measurements is the true concentration says that the measurements
process has no bias. The standard deviation describes the precision of
the measurement.) The laboratory analyzes each specimen <span class="math inline">\(n\)</span> times and
reports the mean result.<br />
Management asks the laboratory to produce results accurate to within
<span class="math inline">\(\pm 0.005\)</span> with 95% confidence. How many measurements must be averaged
to comply with this request?</p>
<p><span class="math display">\[n = \left( \displaystyle \frac{z_{0.025}\,\sigma}{E} \right)^2
    = \Bigl(\frac{1.96 \times 0.0068}{0.005}\Bigr)^2
    \approx 7.1\]</span> Since the sample size should be a whole number, we
round our result up to <span class="math inline">\(n=8\)</span> measurements.</p>
</div>
<p>In Example <a href="confidence-intervals.html#exm:SampleSizePharmaceutical">5.10</a>, we note that 7 measurements
will give a slightly larger margin of error than desired, and 8
measurements a slightly smaller margin of error, the lab must take 8
measurements on each specimen to meet management’s demand. Always round
up to the next higher whole number when finding <span class="math inline">\(n\)</span>.</p>
<div class="example">
<p><span id="exm:unlabeled-div-46" class="example"><strong>Example 5.11  </strong></span>Planning value <span class="math inline">\(\sigma=22.50\)</span>, desired margin <span class="math inline">\(E=2\)</span>.</p>
<ol style="list-style-type: decimal">
<li><p>90% confidence, <span class="math inline">\(z_{0.05}=1.65\)</span>:
<span class="math display">\[n = \Bigl(\frac{1.65 \times 22.50}{2}\Bigr)^2
      \approx 344.6
    \quad\Longrightarrow\quad n = 345.\]</span></p></li>
<li><p>95% confidence, <span class="math inline">\(z_{0.025}=1.96\)</span>:
<span class="math display">\[n = \Bigl(\frac{1.96 \times 22.50}{2}\Bigr)^2
      \approx 486.2
    \quad\Longrightarrow\quad n = 487.\]</span></p></li>
<li><p>99% confidence, <span class="math inline">\(z_{0.005}=2.58\)</span>:
<span class="math display">\[n = \Bigl(\frac{2.58 \times 22.50}{2}\Bigr)^2
      \approx 842.5
    \quad\Longrightarrow\quad n = 843.\]</span></p></li>
</ol>
</div>
</div>
<div id="when-sigma-is-known" class="section level4 unnumbered unlisted hasAnchor">
<h4>When <span class="math inline">\(\sigma\)</span> is Not Known<a href="confidence-intervals.html#when-sigma-is-known" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><strong>Need to Complete</strong></p>
</div>
</div>
<div id="calculating-sample-size-for-a-confidence-interval-on-a-proportion" class="section level3 hasAnchor" number="5.6.2">
<h3><span class="header-section-number">5.6.2</span> Calculating Sample Size for a Confidence Interval on a Proportion<a href="confidence-intervals.html#calculating-sample-size-for-a-confidence-interval-on-a-proportion" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will examine how to calculate the minimum sample size <span class="math inline">\(n\)</span> for a
confidence interval on a proportion for a margin of error <span class="math inline">\(E\)</span> at
confidence level <span class="math inline">\(1-\alpha\)</span>. For sample of size <span class="math inline">\(n\)</span> with unknown
population proportion <span class="math inline">\(p\)</span>:
<span class="math display">\[\hat p \pm z^* \sqrt{ \displaystyle \frac{\hat p(1-\hat p)}{n}}.\]</span>
where the margin of error is
<span class="math display">\[E=z^*\sqrt{ \displaystyle \frac{p^*(1-p^*)}{n}}\]</span> we can rearrange <span class="math inline">\(E\)</span>
to calculate the sample size using
<span class="math display">\[n = \left( \displaystyle \frac{z^*}{E} \right)^2\,p^*(1-p^*),\]</span> where
<span class="math inline">\(p^*\)</span> can be a <em>planning value</em>, which is value obtained from prior
information such as a pilot study. If we do not have any prior
information on <span class="math inline">\(p^*\)</span>, we can use <span class="math inline">\(p^* = 0.5\)</span> which is the conservative
value that maximizes the product <span class="math inline">\(p^*(1-p^*)\)</span>.</p>
<div class="example">
<p><span id="exm:unlabeled-div-47" class="example"><strong>Example 5.12  </strong></span>Aisha Shariff and Yvette Ye are the candidates for mayor in a large
city. You are planning a sample survey to determine what percent of the
voters plan to vote for Shariff. This is a population proportion <span class="math inline">\(p\)</span>.
You will contact an SRS of registered voters in the city. You want to
estimate <span class="math inline">\(p\)</span> with 95% confidence and a margin of error no greater than
3%, or 0.03. How large a sample do you need?<br />
For a 95% CI on <span class="math inline">\(p\)</span>: <span class="math inline">\(z_{0.025} = 1.96\)</span>. Margin of error = 0.03. Since
no information on a good estimate of <span class="math inline">\(p\)</span>, use <span class="math inline">\(p^{*} = 0.5\)</span>.</p>
<p><span class="math display">\[1.96 \sqrt{\frac{(0.5)(1 - 0.5)}{n}} \le 0.03
\quad\Longrightarrow\quad
n = \left(\frac{1.96}{0.03}\right)^{2} (0.5)(0.5) \approx 1067.1.\]</span>
Round up: <span class="math display">\[n = 1068.\]</span></p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-48" class="example"><strong>Example 5.13  </strong></span>The percentage of people not covered by health care insurance in 2007 in
the USA was 15.6%. A congressional committee has been charged with
conducting a sample survey to obtain more current information.</p>
<ol style="list-style-type: decimal">
<li><p>What sample size would you recommend if the committee’s goal is to
estimate the current proportion of individuals without health care
insurance with a margin of error of 0.03? Use a 95% confidence
level.</p></li>
<li><p>Repeat part (a) using a 99% confidence level.</p></li>
</ol>
<p><span class="math display">\[\text{(a) } n
=
\left(\frac{z^{*}}{E}\right)^{2}
p^{*}(1-p^{*}),
\quad z^{*} = 1.96, \; E = 0.03,\; p^{*} = 0.156.\]</span> <span class="math display">\[n
=
\left(\frac{1.96}{0.03}\right)^{2}
(0.156)(1 - 0.156)
\approx 563.\]</span></p>
<p><span class="math display">\[\text{(b) } n
=
\left(\frac{2.58}{0.03}\right)^{2}
(0.156)(1 - 0.156)
\approx 974.\]</span></p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-49" class="example"><strong>Example 5.14  </strong></span>A consumer advocacy group would like to find the proportion of consumers
who bought the newest generation of iPhone and were happy with their
purchase. How large a sample should they take to estimate <span class="math inline">\(p\)</span> with 2%
margin of error and 90% confidence?</p>
<p><strong>Parameters:</strong> <span class="math display">\[\begin{aligned}
E &amp;= 0.02, \quad\text{(margin of error)}\\
\text{Confidence level} &amp;= 0.90 \;\Longrightarrow\; \alpha = 0.10,\;\alpha/2 = 0.05,\\
z^{*} &amp;= z_{0.05} = 1.645,\\
p^{*} &amp;= 0.5,\quad p^{*}(1 - p^{*}) = 0.5 \times 0.5 = 0.25.
\end{aligned}\]</span></p>
<p><strong>Sample‐Size Formula:</strong>
<span class="math display">\[n \;=\; \left(\frac{z^{*}}{E}\right)^{2}\;p^{*}(1 - p^{*}).\]</span></p>
<p>Substituting <span class="math inline">\(z^{*} = 1.645\)</span>, <span class="math inline">\(E = 0.02\)</span>, and <span class="math inline">\(p^{*}(1 - p^{*}) = 0.25\)</span>:
<span class="math display">\[\begin{aligned}
n
&amp;= \left(\frac{1.645}{0.02}\right)^{2} \times 0.25
= \bigl(82.25\bigr)^{2} \times 0.25
= 6{,}764.0625 \times 0.25 \\[0.5em]
&amp;= 1{,}691.015625.
\end{aligned}\]</span></p>
<p>Since <span class="math inline">\(n\)</span> must be a whole number and we always round up to ensure the
margin of error is at most <span class="math inline">\(2\%\)</span>, we take <span class="math display">\[n = 1{,}692.\]</span></p>
</div>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="foundations-of-inference.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": true,
    "facebook": false,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
