<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Simple Linear Regression | Book.knit</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Simple Linear Regression | Book.knit" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Simple Linear Regression | Book.knit" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="analysis-of-variance.html"/>
<link rel="next" href="analysis-of-categorical-data.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/rglWebGL-binding-1.3.24/rglWebGL.js"></script>
<link href="libs/rglwidgetClass-1.3.24/rgl.css" rel="stylesheet" />
<script src="libs/rglwidgetClass-1.3.24/rglClass.min.js"></script>
<script src="libs/CanvasMatrix4-1.3.24/CanvasMatrix.min.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/plotly-binding-4.11.0/plotly.js"></script>
<script src="libs/mathjax-2.7.5/cdn.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>STA258: Statistics with Applied Probability <br> University of Toronto Mississauga</a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html"><i class="fa fa-check"></i>About the Authors</a></li>
<li class="chapter" data-level="" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html"><i class="fa fa-check"></i>Introduction and Overview</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#sec:foundations"><i class="fa fa-check"></i><b>1.1</b> Foundations</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#types-of-data"><i class="fa fa-check"></i><b>1.2</b> Types of data</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#introduction-to-inferential-statistics"><i class="fa fa-check"></i><b>1.3</b> Introduction to Inferential statistics</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html"><i class="fa fa-check"></i><b>2</b> An Introduction to R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#the-statistical-computing-language"><i class="fa fa-check"></i><b>2.1</b> The Statistical Computing Language</a></li>
<li class="chapter" data-level="2.2" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>2.2</b> Installing R and RStudio</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#installing-r"><i class="fa fa-check"></i><b>2.2.1</b> Installing R</a></li>
<li class="chapter" data-level="2.2.2" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#installing-rstudio"><i class="fa fa-check"></i><b>2.2.2</b> Installing RStudio</a></li>
<li class="chapter" data-level="2.2.3" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#positron"><i class="fa fa-check"></i><b>2.2.3</b> Positron</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#an-introduction-to-programming-in-r"><i class="fa fa-check"></i><b>2.3</b> An Introduction to programming in R</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#r-as-a-powerful-calculator"><i class="fa fa-check"></i><b>2.3.1</b> R as a Powerful Calculator</a></li>
<li class="chapter" data-level="2.3.2" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#basic-r-data-structures"><i class="fa fa-check"></i><b>2.3.2</b> Basic R Data Structures</a></li>
<li class="chapter" data-level="2.3.3" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#using-basic-functions-in-r"><i class="fa fa-check"></i><b>2.3.3</b> Using Basic Functions in R</a></li>
<li class="chapter" data-level="2.3.4" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#make-a-histogram-using-rstudio"><i class="fa fa-check"></i><b>2.3.4</b> Make a Histogram Using RStudio</a></li>
<li class="chapter" data-level="2.3.5" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#installing-and-loading-packages"><i class="fa fa-check"></i><b>2.3.5</b> Installing and Loading Packages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>3</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#representing-data"><i class="fa fa-check"></i><b>3.1</b> Representing Data</a></li>
<li class="chapter" data-level="3.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#numerical-measures"><i class="fa fa-check"></i><b>3.2</b> Numerical Measures</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mean"><i class="fa fa-check"></i><b>3.2.1</b> Mean</a></li>
<li class="chapter" data-level="3.2.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#median"><i class="fa fa-check"></i><b>3.2.2</b> Median</a></li>
<li class="chapter" data-level="3.2.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mode"><i class="fa fa-check"></i><b>3.2.3</b> Mode</a></li>
<li class="chapter" data-level="3.2.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#variance"><i class="fa fa-check"></i><b>3.2.4</b> Variance</a></li>
<li class="chapter" data-level="3.2.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#standard-deviation"><i class="fa fa-check"></i><b>3.2.5</b> Standard Deviation</a></li>
<li class="chapter" data-level="3.2.6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#range"><i class="fa fa-check"></i><b>3.2.6</b> Range</a></li>
<li class="chapter" data-level="3.2.7" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#percentiles"><i class="fa fa-check"></i><b>3.2.7</b> Percentiles</a></li>
<li class="chapter" data-level="3.2.8" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#quartiles"><i class="fa fa-check"></i><b>3.2.8</b> Quartiles</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#sec:GraphicalTechniques"><i class="fa fa-check"></i><b>3.3</b> Graphical Techniques</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#histograms"><i class="fa fa-check"></i><b>3.3.1</b> Histograms</a></li>
<li class="chapter" data-level="3.3.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#boxplots"><i class="fa fa-check"></i><b>3.3.2</b> Boxplots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html"><i class="fa fa-check"></i><b>4</b> Foundations of Inference</a>
<ul>
<li class="chapter" data-level="4.1" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#sec:inference"><i class="fa fa-check"></i><b>4.1</b> Some Important Statistical Distributions</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#sec:IntroNormalDist"><i class="fa fa-check"></i><b>4.1.1</b> Introduction to the Normal Distribution</a></li>
<li class="chapter" data-level="4.1.2" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#introduction-to-the-chi-square-distribution"><i class="fa fa-check"></i><b>4.1.2</b> Introduction to the Chi-Square distribution</a></li>
<li class="chapter" data-level="4.1.3" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#introduction-to-the-t-distribution"><i class="fa fa-check"></i><b>4.1.3</b> Introduction to the t-Distribution</a></li>
<li class="chapter" data-level="4.1.4" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#introduction-to-the-f-distribution"><i class="fa fa-check"></i><b>4.1.4</b> Introduction to the F-Distribution</a></li>
<li class="chapter" data-level="4.1.5" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#arithmetics-of-rvs"><i class="fa fa-check"></i><b>4.1.5</b> Arithmetics of RV’s</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#sampling-distributions"><i class="fa fa-check"></i><b>4.2</b> Sampling Distributions</a></li>
<li class="chapter" data-level="4.3" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>4.3</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="4.4" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#law-of-large-numbers"><i class="fa fa-check"></i><b>4.4</b> Law of Large Numbers</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#convergence-in-probability"><i class="fa fa-check"></i><b>4.4.1</b> Convergence in Probability</a></li>
<li class="chapter" data-level="4.4.2" data-path="foundations-of-inference.html"><a href="foundations-of-inference.html#weak-law-of-large-numbers-wlln"><i class="fa fa-check"></i><b>4.4.2</b> Weak Law of Large Numbers (WLLN)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="confidence-intervals.html"><a href="confidence-intervals.html"><i class="fa fa-check"></i><b>5</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="5.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#introduction-1"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#interpretation"><i class="fa fa-check"></i><b>5.2</b> Interpretation</a></li>
<li class="chapter" data-level="5.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#one-sample-confidence-intervals"><i class="fa fa-check"></i><b>5.3</b> One Sample Confidence Intervals</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#on-a-population-mean"><i class="fa fa-check"></i><b>5.3.1</b> On a Population Mean</a></li>
<li class="chapter" data-level="5.3.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#on-a-population-proportion"><i class="fa fa-check"></i><b>5.3.2</b> On a Population Proportion</a></li>
<li class="chapter" data-level="5.3.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#on-a-population-variance"><i class="fa fa-check"></i><b>5.3.3</b> On a Population Variance</a></li>
<li class="chapter" data-level="5.3.4" data-path="confidence-intervals.html"><a href="confidence-intervals.html#assumptions"><i class="fa fa-check"></i><b>5.3.4</b> Assumptions</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="confidence-intervals.html"><a href="confidence-intervals.html#two-sample-confidence-intervals"><i class="fa fa-check"></i><b>5.4</b> Two Sample Confidence Intervals</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#on-a-difference-of-means"><i class="fa fa-check"></i><b>5.4.1</b> On a Difference of Means</a></li>
<li class="chapter" data-level="5.4.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#on-a-difference-of-proportions"><i class="fa fa-check"></i><b>5.4.2</b> On a Difference of Proportions</a></li>
<li class="chapter" data-level="5.4.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#on-a-ratio-of-variances"><i class="fa fa-check"></i><b>5.4.3</b> On a Ratio of Variances</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="confidence-intervals.html"><a href="confidence-intervals.html#sec:CIsOnPaired"><i class="fa fa-check"></i><b>5.5</b> Confidence Intervals on Paired Data</a></li>
<li class="chapter" data-level="5.6" data-path="confidence-intervals.html"><a href="confidence-intervals.html#sample-size-selection-using-confidence-intervals"><i class="fa fa-check"></i><b>5.6</b> Sample Size Selection using Confidence Intervals</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#secSampleSizeCIMean"><i class="fa fa-check"></i><b>5.6.1</b> Calculating Sample Size for a Confidence Interval on a Mean</a></li>
<li class="chapter" data-level="5.6.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#calculating-sample-size-for-a-confidence-interval-on-a-proportion"><i class="fa fa-check"></i><b>5.6.2</b> Calculating Sample Size for a Confidence Interval on a Proportion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html"><i class="fa fa-check"></i><b>6</b> Hypothesis Tests</a>
<ul>
<li class="chapter" data-level="6.1" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html#introduction-2"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html#one-sample-hypothesis-tests"><i class="fa fa-check"></i><b>6.2</b> One Sample Hypothesis Tests</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html#on-a-population-mean-1"><i class="fa fa-check"></i><b>6.2.1</b> On a Population Mean</a></li>
<li class="chapter" data-level="6.2.2" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html#on-a-population-proportion-1"><i class="fa fa-check"></i><b>6.2.2</b> On a Population Proportion</a></li>
<li class="chapter" data-level="6.2.3" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html#on-a-population-variance-1"><i class="fa fa-check"></i><b>6.2.3</b> On a Population Variance</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html#two-sample-hypothesis-tests"><i class="fa fa-check"></i><b>6.3</b> Two Sample Hypothesis Tests</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html#on-a-difference-of-means-1"><i class="fa fa-check"></i><b>6.3.1</b> On a Difference of Means</a></li>
<li class="chapter" data-level="6.3.2" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html#on-a-difference-of-proportions-1"><i class="fa fa-check"></i><b>6.3.2</b> On a Difference of Proportions</a></li>
<li class="chapter" data-level="6.3.3" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html#sec:RatioVars"><i class="fa fa-check"></i><b>6.3.3</b> On a Ratio of Variances</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="hypothesis-tests.html"><a href="hypothesis-tests.html#hypothesis-tests-on-paired-data"><i class="fa fa-check"></i><b>6.4</b> Hypothesis Tests on Paired Data</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="statistical-power.html"><a href="statistical-power.html"><i class="fa fa-check"></i><b>7</b> Statistical Power</a>
<ul>
<li class="chapter" data-level="7.1" data-path="statistical-power.html"><a href="statistical-power.html#introduction-3"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="statistical-power.html"><a href="statistical-power.html#type-i-and-type-ii-errors"><i class="fa fa-check"></i><b>7.2</b> Type I and Type II Errors</a></li>
<li class="chapter" data-level="7.3" data-path="statistical-power.html"><a href="statistical-power.html#using-power-to-determine-sample-size"><i class="fa fa-check"></i><b>7.3</b> Using Power to Determine Sample Size</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>8</b> Analysis of Variance</a></li>
<li class="chapter" data-level="9" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>9</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#introduction-to-the-linear-model"><i class="fa fa-check"></i><b>9.1</b> Introduction to the Linear Model</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#sec:LeastSquaresMethod"><i class="fa fa-check"></i><b>9.1.1</b> Least Squares Method</a></li>
<li class="chapter" data-level="9.1.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#estimating-parameters-for-the-simple-linear-model"><i class="fa fa-check"></i><b>9.1.2</b> Estimating Parameters for the Simple Linear Model</a></li>
<li class="chapter" data-level="9.1.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#measures-of-linear-relationship"><i class="fa fa-check"></i><b>9.1.3</b> Measures of Linear Relationship</a></li>
<li class="chapter" data-level="9.1.4" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#sse-ssr-and-sst"><i class="fa fa-check"></i><b>9.1.4</b> SSE, SSR and SST</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#inference-for-simple-linear-regression"><i class="fa fa-check"></i><b>9.2</b> Inference for Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#estimating-variance-in-linear-regression"><i class="fa fa-check"></i><b>9.2.1</b> Estimating Variance in Linear Regression</a></li>
<li class="chapter" data-level="9.2.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#confidence-intervals-and-hypothesis-tests"><i class="fa fa-check"></i><b>9.2.2</b> Confidence Intervals and Hypothesis Tests</a></li>
<li class="chapter" data-level="9.2.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#anova-table-for-simple-linear-regression"><i class="fa fa-check"></i><b>9.2.3</b> ANOVA Table for Simple Linear Regression</a></li>
<li class="chapter" data-level="9.2.4" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#residual-plots"><i class="fa fa-check"></i><b>9.2.4</b> Residual Plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="analysis-of-categorical-data.html"><a href="analysis-of-categorical-data.html"><i class="fa fa-check"></i><b>10</b> Analysis of Categorical Data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="analysis-of-categorical-data.html"><a href="analysis-of-categorical-data.html#multinomial-response-model"><i class="fa fa-check"></i><b>10.1</b> Multinomial Response Model</a></li>
<li class="chapter" data-level="10.2" data-path="analysis-of-categorical-data.html"><a href="analysis-of-categorical-data.html#the-chi-square-test-for-goodness-of-fit"><i class="fa fa-check"></i><b>10.2</b> The Chi-square Test for Goodness of fit</a></li>
<li class="chapter" data-level="10.3" data-path="analysis-of-categorical-data.html"><a href="analysis-of-categorical-data.html#sample-size-assumption"><i class="fa fa-check"></i><b>10.3</b> Sample Size Assumption</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="simple-linear-regression" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">Chapter 9</span> Simple Linear Regression<a href="simple-linear-regression.html#simple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introduction-to-the-linear-model" class="section level2 hasAnchor" number="9.1">
<h2><span class="header-section-number">9.1</span> Introduction to the Linear Model<a href="simple-linear-regression.html#introduction-to-the-linear-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A linear model is a function the form</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \ldots + \beta_p x_{ip} + \varepsilon_i, \quad \varepsilon_i \sim N(0, \sigma^2)\]</span></p>
<p>where <span class="math inline">\(y\)</span> is the <em>response</em> (also called the <em>outcome</em> or <em>dependent</em>) variable, <span class="math inline">\((x_{i1},\dots,x_{ip})\)</span> are the <em>predictors</em> (also called <em>explanatory</em> or <em>independent</em> variables or <em>covariates</em>) and <span class="math inline">\(\varepsilon_i\)</span> is random error.
In practice, the aim of constructing a linear model is usually prediction using the <span class="math inline">\(x_{ij}\)</span> to predict <span class="math inline">\(y\)</span>, and to conduct statistical inference to assess whether <span class="math inline">\(y\)</span> is related to the predictors, such as testing for association.
In this mode, <span class="math inline">\(x_{ij}\)</span> are assumed fixed, <span class="math inline">\(y_i\)</span> are random and the error terms <span class="math inline">\(\varepsilon_i\)</span> is independent Gaussian noise with a constant variance <span class="math inline">\(\sigma^2\)</span>.
The coefficients <span class="math inline">\(\beta_0, \ldots, \beta_p\)</span> are fixed but unknown constants.</p>
<p>A simple linear regression (SLR) model is a linear regression model with just 1 predictor and it has the form</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1 x_{i} \varepsilon_i, \quad \varepsilon_i \sim N(0, \sigma^2).\]</span></p>
<div id="sec:LeastSquaresMethod" class="section level3 hasAnchor" number="9.1.1">
<h3><span class="header-section-number">9.1.1</span> Least Squares Method<a href="simple-linear-regression.html#sec:LeastSquaresMethod" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The method of least squares is an optimization technique used to calculate the coefficients <span class="math inline">\(\beta_0, \ldots, \beta_p\)</span> in regression analysis. Its goal is to determine the parameters of a candidate model that make the model’s predictions as close as possible to the observed data
based on some minimization criteria.</p>
<p>An important definition which is used in evaluating the fit of a model is the following</p>
<div class="definition">
<p><span id="def:Residual" class="definition"><strong>Definition 9.1  (Residual) </strong></span>A <em>residual</em> (<span class="math inline">\(e_{i}\)</span>) is the distance between an observed data point <span class="math inline">\(y_i\)</span> and a fitted value from a regression model <span class="math inline">\(\hat{y}_{i}\)</span>.
<span class="math display">\[
\begin{aligned}
\text{residual}  &amp; = (\text{observed data point}) - (\text{fitted value})  \\
e_{i}            &amp; = y_{i} - \hat{y}_{i}
\end{aligned}
\]</span></p>
</div>
<p>The data points <span class="math inline">\((x_{i1},\dots,x_{ip}, y_{i})\)</span> are observed values.
To calculate a residual for an observed <span class="math inline">\(y_{i}\)</span>, we would plug in the <span class="math inline">\(x_{i1},\dots,x_{ip}\)</span> values for this measurement into the model to evaluate the corresponding <span class="math inline">\(\hat{y}_{i}\)</span>. Once we have this value, we can evaluate the residual as the difference <span class="math inline">\(e_{i} = y_{i} - \hat{y}_{i}\)</span>.</p>
<p>Given a sample of <span class="math inline">\(n\)</span> observations, we consider the sum of the square distances between each observed <span class="math inline">\(y_i\)</span> and corresponding predicted <span class="math inline">\(\hat{y}_i\)</span> (i.e. the sum of the square residuals) which is given by the model.
This quantity which we minimize to find the model of best fit is called the Sum of Square Errors (SSE):
<span class="math display">\[
\begin{align}
\mathrm{SSE}  &amp;= \sum_{i=1}^n e_{i}^2  \\
              &amp;= \sum_{i=1}^n \big(y_i - \hat y_i\big)^2  \\
              &amp;= \sum_{i=1}^n \bigl(y_i - (\beta_0 + \beta_1 x_{i1} + \cdots + \beta_p x_{ip})\bigr)^2.
\end{align}
\]</span>
The goal of the least‑squares technique is to find <span class="math inline">\(\beta_0,\dots,\beta_p\)</span> such that the SSE is as small as possible.
This can formally be written as:</p>
<p><span class="math display">\[
\begin{align}
&amp; \text{solve}\quad \min_{\beta_0,\beta_1,\dots,\beta_p}\; \frac{1}{2}\sum_{i=1}^{n}\left(y_i - \beta_0 - \sum_{j=1}^{p}\beta_j x_{ij}\right)^2\\
&amp; \text{such that}\quad \beta_0,\dots,\beta_p \in \mathbb{R}.
\end{align}
\]</span>
This can also be represented in vector-matrix form as</p>
<p><span class="math display">\[
\begin{align}
&amp; \text{solve}\quad \min_{\beta\in\mathbb{R}^{p+1}} \;\frac{1}{2}\,(y - X\beta)^{\!\top}(y - X\beta)  \\
&amp; \text{such that}\quad \beta \in \mathbb{R}^{p+1}.
\end{align}
\]</span>
where
<span class="math display">\[
\begin{align*}
&amp;\textbf{y}\in\mathbb{R}^{n}\ \text{is a response vector }(y_1,\dots,y_n)^{\top}.\\
&amp;\textbf{X}\in\mathbb{R}^{n\times(p+1)}\ \text{is a design matrix }[\,\mathbf{1}\ \ x_1\ \ \cdots\ \ x_p\,],\ \text{with first column of ones (intercept)}.\\
&amp;\boldsymbol{\beta}\in\mathbb{R}^{p+1}\ \text{is a vector if parameters }(\beta_0,\beta_1,\dots,\beta_p)^{\top}.\\
\end{align*}
\]</span>
Using matrix calculus, we can show the solution for the least squares optimization problem is</p>
<p><span class="math display">\[
\hat{\beta} = (X^{\top}X)^{-1} X^{\top} y
\]</span></p>
<p>The resulting fitted values take the form
<span class="math display">\[
    \hat y_i
    \;=\;
    \hat\beta_0 + \hat\beta_1\,x_{i1} + \cdots + \hat\beta_p\,x_{ip}.
\]</span></p>
<p>Here, <span class="math inline">\(\hat\beta_0\)</span> is the intercept which is the predicted value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x_{i1}, \ldots, x_{ip}\)</span> are all 0,
and each <span class="math inline">\(\hat\beta_j\)</span> for <span class="math inline">\(j=1,\dots,p\)</span> is the change in the expected response for a one‑unit increase in the corresponding predictor
with all other predictor values held fixed.</p>
<p>In this course, we will focus on the simplest nontrivial case of a single predictor
<span class="math display">\[
    \hat{y} \;=\; \beta_0 + \beta_1\,x,
\]</span>
where <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> denote the intercept and slope of the fitted line.</p>
</div>
<div id="estimating-parameters-for-the-simple-linear-model" class="section level3 hasAnchor" number="9.1.2">
<h3><span class="header-section-number">9.1.2</span> Estimating Parameters for the Simple Linear Model<a href="simple-linear-regression.html#estimating-parameters-for-the-simple-linear-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let <span class="math inline">\((x_1, y_1), (x_2, y_2), \ldots, (x_n, y_n)\)</span> be pairs of <em>observed</em> data points
for independent variable <span class="math inline">\(x\)</span> and dependent variable <span class="math inline">\(y\)</span>.
Suppose we plot these points on coordinate axes (See Figure <a href="simple-linear-regression.html#fig:PlotPointsOnly">9.1</a>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:PlotPointsOnly"></span>
<img src="Book_Files/figure-html/PlotPointsOnly-1.png" alt="Example of points plotted on coordinate axes." width="672" />
<p class="caption">
Figure 9.1: Example of points plotted on coordinate axes.
</p>
</div>
<p>Our goal is to find the line of best fit for these points.
The line of best fit will be of the form
<span class="math display">\[
\hat{y} = \hat{\beta}_{0} + \hat{\beta}_{1}x
\]</span>
where <span class="math inline">\(\hat{y}\)</span> represents all fitted points on the line, <span class="math inline">\(x\)</span> is a value we can input into calculate a predicted <span class="math inline">\(\hat{y}\)</span>, <span class="math inline">\(\hat{\beta}_0\)</span> is the estimate of the intercept and <span class="math inline">\(\hat{\beta}_1\)</span> is the estimate of the slope (See Figure <a href="simple-linear-regression.html#fig:PlotPointsLine">9.2</a>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:PlotPointsLine"></span>
<img src="Book_Files/figure-html/PlotPointsLine-1.png" alt="The line of best fit has now been superimposed on the points in Figure \@ref(fig:PlotPointsOnly)." width="672" />
<p class="caption">
Figure 9.2: The line of best fit has now been superimposed on the points in Figure <a href="simple-linear-regression.html#fig:PlotPointsOnly">9.1</a>.
</p>
</div>
<p>Recall in Section <a href="simple-linear-regression.html#sec:LeastSquaresMethod">9.1.1</a> that we discussed that the technique used to determine the line of best fit is to minimize the sum the squared distances between the observed <span class="math inline">\(y_{i}\)</span>’s from our data and the fitter <span class="math inline">\(\hat{y}_{i}\)</span>’s which are predicted from the line (See Figure <a href="simple-linear-regression.html#fig:PlotPtsLnRes">9.3</a>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:PlotPtsLnRes"></span>
<img src="Book_Files/figure-html/PlotPtsLnRes-1.png" alt="The distances between each observed $y_i$ and fitted $\hat{y}_{i}$ from Figure \@ref(fig:PlotPointsLine)." width="672" />
<p class="caption">
Figure 9.3: The distances between each observed <span class="math inline">\(y_i\)</span> and fitted <span class="math inline">\(\hat{y}_{i}\)</span> from Figure <a href="simple-linear-regression.html#fig:PlotPointsLine">9.2</a>.
</p>
</div>
<p>The square error (SSE) for the simple linear regression model is</p>
<p><span class="math display">\[
\begin{aligned}
\mathrm{SSE}
  &amp;= \sum_{i=1}^{n} (y_i - \hat{y}_{i})^2\\
  &amp;= \sum_{i=1}^{n} \big(y_i - (\hat{\beta}_0 + \hat{\beta}_1x_i) \big)^2.
\end{aligned}
\]</span>
The find the values of <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span> which minimizes the SSSE, we take the partial derivatives of the SSE with respect to <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span>, setting the expression to 0 and solving for each term, we obtain</p>
<div class="definition">
<p><span id="def:unlabeled-div-93" class="definition"><strong>Definition 9.2  </strong></span>For a model of the form <span class="math inline">\(y = \beta_{0} + \beta_{1}x + \varepsilon, \, \varepsilon \sim N(0, \sigma^2)\)</span>, the least square estimates for <span class="math inline">\(\beta_{0}\)</span> and <span class="math inline">\(\beta_{1}\)</span> are given by
<span class="math display">\[
\begin{aligned}
\hat{\beta}_1 &amp;= \frac{SS_{xy}}{SS_{xx}}
                  = \frac{\displaystyle\sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y}) }{ \displaystyle\sum_{i=1}^{n} (x_i - \bar{x})^2 }
                  = \frac{\displaystyle\sum_{i=1}^{n}x_iy_i - n\bar{x}\bar{y}}{\displaystyle\sum_{i=1}^{n}x_i^2 - n\bar{x}^2}\\
\hfill\\
\text{and}\\
\hfill\\
\hat{\beta}_0 &amp;= \bar{y} - \hat{\beta}_1\bar{x}
\end{aligned}
\]</span></p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-94" class="example"><strong>Example 9.1  </strong></span>Suppose an appliance store conducts a 5-month experiment to determine
the effect of advertising on sales revenue. The results are shown in a
table below. The relationship between sales revenue, <span class="math inline">\(y\)</span>, and
advertising expenditure, <span class="math inline">\(x\)</span>, is hypothesized to follow a ﬁrst-order
linear model, that is, <span class="math inline">\(y = \beta_0 + \beta_1\cdot x + \varepsilon\)</span>, where
<span class="math inline">\(y =\)</span> dependent variable, <span class="math inline">\(x =\)</span> independent variable, <span class="math inline">\(\beta_0\)</span>
y-intercept, <span class="math inline">\(\beta_1 =\)</span> slope of the line and <span class="math inline">\(\varepsilon =\)</span> error
variable.</p>
<div class="smalltbl">
<table>
<thead>
<tr class="header">
<th align="center">Day</th>
<th align="center">Number of tools (X)</th>
<th align="center">Electricity costs (Y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">7</td>
<td align="center">23.80</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">3</td>
<td align="center">11.89</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">2</td>
<td align="center">15.89</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">5</td>
<td align="center">26.11</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">8</td>
<td align="center">31.79</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">11</td>
<td align="center">39.93</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="center">5</td>
<td align="center">12.27</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td align="center">15</td>
<td align="center">40.06</td>
</tr>
<tr class="odd">
<td align="center">9</td>
<td align="center">3</td>
<td align="center">21.38</td>
</tr>
<tr class="even">
<td align="center">10</td>
<td align="center">6</td>
<td align="center">18.65</td>
</tr>
</tbody>
</table>
</div>
<p>a) Obtain the least squares estimates of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, and
state the estimated regression function.</p>
<p>b) Plot the estimated regression function and the data.</p>
<p><strong>Solution:</strong></p>
<p>a) <span class="math inline">\(\bar{x} = 3\)</span>, <span class="math inline">\(\bar{y} = 2\)</span>, <span class="math inline">\(S_{xx} = 10\)</span>, <span class="math inline">\(S_{xy} = 7\)</span></p>
<p>Then, the slope of the least squares line is
<span class="math inline">\(\hat{\beta}_1 = \frac{S_{xy}}{S_{xx}} = 0.7\)</span> and
<span class="math inline">\(\hat{\beta}_0 = \bar{y} - \hat{\beta}_1\bar{x} = -0.1\)</span>. Thus, the least
squares line is <span class="math inline">\(\hat{y} = -0.1 + 0.7x\)</span>.</p>
<p>b) R-code</p>
<div class="tcolorbox">
<pre><code>plot(x, y, main=&quot;Scatterplot: Simple Linear Regression&quot;,
xlab=&quot;x&quot;, ylab=&quot;y&quot;, pch=19,col=&quot;blue&quot;);

abline(coef(linear.reg), col=&quot;red&quot;,lty=2);</code></pre>
</div>
</div>
<!-- By taking partial derivatives of the residual sum of squares with respect to $b_0$ and $b_1$ and setting them to zero, one obtains the classical normal equations.   -->
<!-- Their solution yields the familiar closed‑form formulas -->
<!-- \[ -->
<!--     b_1 \;=\; r\,\frac{s_y}{s_x}, -->
<!--     \qquad -->
<!--     b_0 \;=\; \bar y \;-\; b_1\,\bar x, -->
<!-- \] -->
<!-- where $r$ is the sample correlation between $x$ and $y$, and $s_x$, $s_y$ denote their sample standard deviations. -->
<div class="remark">
<p><span id="unlabeled-div-95" class="remark"><em>Remark</em>. </span></p>
<ul>
<li><p>The distinction between explanatory and response variables is
essential in Least Squares Method.</p></li>
<li><p>The least-squares line (trendline) always passes through the point
(<span class="math inline">\(\bar{x}\)</span>, <span class="math inline">\(\bar{y}\)</span>) on the graph of <span class="math inline">\(y\)</span> against <span class="math inline">\(x\)</span>.</p></li>
<li><p>The square of the correlation, <span class="math inline">\(r^2\)</span>, is the fraction of the variation
in the values of <span class="math inline">\(y\)</span> that is explained by the variation in <span class="math inline">\(x\)</span>.</p></li>
</ul>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-96" class="example"><strong>Example 9.2  </strong></span>A tool die maker operates out of a small shop making specialized tools.
He is considering increasing the size of his business and needs to know
more about his costs. One such cost is electricity, which he needs to
operate his machines and lights. He keeps track of his daily electricity
costs and the number of tools that he made that day. These data are
listed next. Determine the fixed and variable electricity costs using
the Least Squares Method.</p>
<div class="smalltl">
<table>
<thead>
<tr class="header">
<th align="center">Day</th>
<th align="center">Number of tools (X)</th>
<th align="center">Electricity costs (Y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">7</td>
<td align="center">23.80</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">3</td>
<td align="center">11.89</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">2</td>
<td align="center">15.89</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">5</td>
<td align="center">26.11</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">8</td>
<td align="center">31.79</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">11</td>
<td align="center">39.93</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="center">5</td>
<td align="center">12.27</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td align="center">15</td>
<td align="center">40.06</td>
</tr>
<tr class="odd">
<td align="center">9</td>
<td align="center">3</td>
<td align="center">21.38</td>
</tr>
<tr class="even">
<td align="center">10</td>
<td align="center">6</td>
<td align="center">18.65</td>
</tr>
</tbody>
</table>
</div>
<p>Solution:</p>
<p>Step 1: Entering Data;</p>
<div class="tcolorbox">
<pre><code>tools=c(7,3,2,5,8,11,5,15,3,6);

cost=c(23.80,11.89,15.98,26.11,31.79, 39.93,12.27,40.06,21.38,18.65);</code></pre>
</div>
<p>Step 2: Finding Slope;</p>
<div class="tcolorbox">
<pre><code>Sx=sd(tools); 

Sy=sd(cost); 

r=cor(tools,cost); 

b1=r*(Sy/Sx); 

b1;
 
## [1] 2.245882</code></pre>
</div>
<p>Step 3: Finding <span class="math inline">\(y\)</span>-intercept;</p>
<div class="tcolorbox">
<pre><code>x.bar=mean(tools); 

y.bar=mean(cost);

b0=y.bar - b1*x.bar;

b0; 

## [1] 9.587765</code></pre>
</div>
<p>We can also use R-code to draw a graph:</p>
<div class="tcolorbox">
<pre><code>plot(tools,cost,pch=19);

abline(least.squares$coeff,col=&quot;red&quot;);

# pch=19 tells R to draw solid circles; 

# abline tells R to add trendline;</code></pre>
</div>
<p>Interpretation:</p>
<p>The slope measures the marginal rate of change in the dependent
variable. In this example, the slope is <span class="math inline">\(2.25\)</span>, which means that in this
sample, for each one-unit increase in the number of tools, the marginal
increase in the electricity cost is <span class="math inline">\(\$ 2.25\)</span> per tool.</p>
<p>The <span class="math inline">\(y\)</span>-intercept is <span class="math inline">\(9.57\)</span>; that is, the line strikes the <span class="math inline">\(y\)</span>-axis at
<span class="math inline">\(9.57\)</span>. However, when <span class="math inline">\(x = 0\)</span>, we are producing no tools and hence the
estimated ﬁxed cost of electricity is <span class="math inline">\(\$9.57\)</span> per day .</p>
</div>
</div>
<div id="measures-of-linear-relationship" class="section level3 hasAnchor" number="9.1.3">
<h3><span class="header-section-number">9.1.3</span> Measures of Linear Relationship<a href="simple-linear-regression.html#measures-of-linear-relationship" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We begin be introducing a quantitaive measurement to
measure the linear relationship between variavles</p>
<p><strong>Covariance (Sample Covariance)</strong></p>
<p>In probability theory and statistics, covariance is a measure of the
joint variability of two random variables. The covariance sign shows the
direction of the linear relationship between two variables. If higher
values of one variable tend to occur with higher values of the other
(and lower with lower), the covariance is positive, meaning the
variables move in the same direction. If higher values of one variable
tend to occur with lower values of the other, the covariance is
negative, meaning they move in opposite directions. The size (magnitude)
of the covariance reflects how much the two variables vary together,
based on the variances they share.</p>
<div class="definition">
<p><span id="def:unlabeled-div-97" class="definition"><strong>Definition 9.3  </strong></span>The sample covariance for 2 variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is:
<span class="math display">\[s_{xy} = \frac{1}{n-1} \cdot \sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y}) = \frac{\sum_{i = 1}^{n}x_i \cdot y_i}{n -1} - \frac{n\bar{x}\bar{y}}{n-1}.\]</span>
These are the two ways to compute covariance. Both will give you the
same answer.</p>
</div>
<p>The covariance is a measures of how two variables move together.</p>
<ul>
<li><p>If covariance of two random variables is greater than <span class="math inline">\(0\)</span>,
(<span class="math inline">\(cov(x,y) &gt; 0\)</span>), then the two random variables show the same trend.
That is: if one random variable is increasing, then the other one is
also increasing; while if one random variable is decreasing, then the
other one is also decreasing.</p></li>
<li><p>If covariance of two random variables is less than <span class="math inline">\(0\)</span>,
(<span class="math inline">\(cov(x,y) &lt; 0\)</span>), then the two random variables show the opposite
trend. That is: if one random variable is increasing, then the other
one is decreasing; while if one random variable is decreasing, then
the other one is increasing.</p></li>
<li><p>If covariance of two random variables is equal to <span class="math inline">\(0\)</span>,
(<span class="math inline">\(cov(x,y) = 0\)</span>), then we say that there is no relationship
(systematically linear) between the two random variables.</p></li>
</ul>
<p>Note that covariance is not standardized, so it can be difficult to
interpret directly.</p>
<p><strong>Coefficient of Correlation</strong></p>
<p>In statistics, correlation or dependence is any statistical
relationship, whether causal or not, between two random variables or
bivariate data. It helps us understand whether and how changes in one
variable are associated with changes in another. A positive correlation
means that as one variable increases, the other tends to increase as
well, while a negative correlation means that one variable tends to
decrease as the other increases. The degree of correlation is usually
expressed with a correlation coefficient, which ranges from <span class="math inline">\(-1\)</span> to
<span class="math inline">\(+1\)</span>.</p>
<div class="definition">
<p><span id="def:unlabeled-div-98" class="definition"><strong>Definition 9.4  </strong></span>The coefficient of correlation is given by:
<span class="math display">\[r_{xy} = \frac{s_{xy}}{s_x \cdot s_y}.\]</span>
where</p>
<p><span class="math inline">\(r_{xy}\)</span> , is the sample correlation coefficient; <br>
<span class="math inline">\(s_{xy}\)</span> , is the sample covariance; <br>
<span class="math inline">\(s_{x}\)</span> , is the sample standard deviation of <span class="math inline">\(x\)</span>; <br>
<span class="math inline">\(s_{y}\)</span> , is the sample standard deviation of <span class="math inline">\(y\)</span>.</p>
</div>
<p>The correlation r measures the strength and direction of the linear
association between two quantitative variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>. Although you
calculate a correlation for any scatter plot, <span class="math inline">\(r\)</span> measures only
straight-line relationships. In short, coefficient of correlation is a
measure of the strength of the linear relationship between two random
variables.</p>
<ul>
<li>If <span class="math inline">\(r_{xy} \approx +1\)</span>, then we say that the two random variables have
strong positive correlation (See Figure <a href="simple-linear-regression.html#fig:examplePositiveCorr">9.4</a>).</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:examplePositiveCorr"></span>
<div class="plotly html-widget html-fill-item" id="htmlwidget-e1b8784ad4f169edbcfb" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-e1b8784ad4f169edbcfb">{"x":{"visdat":{"7996a0e8752":["function () ","plotlyVisDat"]},"cur_data":"7996a0e8752","attrs":{"7996a0e8752":{"x":{},"y":{},"mode":"markers","marker":{"color":"#619CFF","size":8},"name":"Data points","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Example of Positive Correlation","xaxis":{"domain":[0,1],"automargin":true,"title":"X"},"yaxis":{"domain":[0,1],"automargin":true,"title":"Y"},"legend":{"x":0.050000000000000003,"y":0.94999999999999996},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[4,4.2068965517241379,4.4137931034482758,4.6206896551724137,4.8275862068965516,5.0344827586206895,5.2413793103448274,5.4482758620689653,5.6551724137931032,5.8620689655172411,6.068965517241379,6.2758620689655178,6.4827586206896548,6.6896551724137936,6.8965517241379306,7.1034482758620694,7.3103448275862064,7.5172413793103452,7.7241379310344822,7.931034482758621,8.137931034482758,8.3448275862068968,8.5517241379310356,8.7586206896551726,8.9655172413793096,9.1724137931034484,9.3793103448275872,9.5862068965517242,9.7931034482758612,10],"y":[67.197621767238942,69.883595311204303,79.862507087986998,73.455990232984945,74.784369710287493,83.747738727519845,78.511477581670135,70.916073137312154,74.841597809497898,77.082034977086423,86.465236573404198,83.178379480114401,84.417650356418534,84.001689441794568,81.703552946919274,94.451807063325745,89.040976529077227,77.753121113403537,92.127469162990835,87.291215375153442,85.350536642479568,90.634263357742995,87.628598448118979,90.148647301820176,91.702389867650254,87.428602411805173,101.08548694661056,98.697900071941191,93.274832556319566,106.26907460534963],"mode":"markers","marker":{"color":"#619CFF","size":8,"line":{"color":"rgba(31,119,180,1)"}},"name":"Data points","type":"scatter","error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"line":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p class="caption">
Figure 9.4: An illustration of strong negative correlation (<span class="math inline">\(r_{xy} \approx +1\)</span>).
</p>
</div>
<ul>
<li>If <span class="math inline">\(r_{xy} \approx -1\)</span>, then we say that the two random variables have
strong negative correlation. (See figure <a href="simple-linear-regression.html#fig:exampleNegaticeCorr">9.5</a>)</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:exampleNegaticeCorr"></span>
<div class="plotly html-widget html-fill-item" id="htmlwidget-17a3cf5b06c3cfe94bb2" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-17a3cf5b06c3cfe94bb2">{"x":{"visdat":{"79974fce1fc":["function () ","plotlyVisDat"]},"cur_data":"79974fce1fc","attrs":{"79974fce1fc":{"x":{},"y":{},"mode":"markers","marker":{"color":"#619CFF","size":8},"name":"Data Points","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Example of Negative Correlation","xaxis":{"domain":[0,1],"automargin":true,"title":"X"},"yaxis":{"domain":[0,1],"automargin":true,"title":"Y"},"legend":{"x":0.050000000000000003,"y":0.94999999999999996},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[40,42.068965517241381,44.137931034482762,46.206896551724142,48.275862068965516,50.344827586206897,52.413793103448278,54.482758620689658,56.551724137931032,58.620689655172413,60.689655172413794,62.758620689655174,64.827586206896555,66.896551724137936,68.965517241379317,71.034482758620697,73.103448275862064,75.172413793103459,77.241379310344826,79.310344827586206,81.379310344827587,83.448275862068968,85.517241379310349,87.58620689655173,89.65517241379311,91.724137931034477,93.793103448275872,95.862068965517238,97.931034482758633,100],"y":[2.3879048706895576,2.3310136824312124,2.5773666628298249,2.1782807827625268,2.0972861184607607,2.3293143672396699,2.0000779780399456,1.5824307910533766,1.6309221125481241,1.6167499589211847,1.892543632215165,1.665369358818066,1.6227074816081719,1.516981904013766,1.338831773049185,1.7651496176518777,1.4674946239477347,0.93695179803187023,1.4349140374555942,1.1663112836718046,1.0152488181246648,1.1547521245063574,0.96415394904822938,0.99595403760633883,0.99037676181476386,0.7528869017612918,1.2337338794871402,1.0738400911932022,0.79349937316099073,1.2507629842139854],"mode":"markers","marker":{"color":"#619CFF","size":8,"line":{"color":"rgba(31,119,180,1)"}},"name":"Data Points","type":"scatter","error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"line":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p class="caption">
Figure 9.5: An illustration of strong negative correlation (<span class="math inline">\(r_{xy} \approx -1\)</span>).
</p>
</div>
<ul>
<li>If <span class="math inline">\(r_{xy} \approx 0\)</span>, then we say that there is essentially no
correlation between the two random variables. Note that if
<span class="math inline">\(r \approx 0\)</span>, then it suggests a linear relationship doesn’t exist
but other relationship may exist (See Figure <a href="simple-linear-regression.html#fig:exampleNoCorr">9.6</a>).</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:exampleNoCorr"></span>
<div class="plotly html-widget html-fill-item" id="htmlwidget-a1e7228fd68eb5cfaf36" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-a1e7228fd68eb5cfaf36">{"x":{"visdat":{"79975ba679e":["function () ","plotlyVisDat"]},"cur_data":"79975ba679e","attrs":{"79975ba679e":{"x":{},"y":{},"mode":"markers","marker":{"color":"rgba(0, 100, 255, 0.7)","size":8},"name":"Data points","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Example of No Correlation","xaxis":{"domain":[0,1],"automargin":true,"title":"X"},"yaxis":{"domain":[0,1],"automargin":true,"title":"Y"},"legend":{"x":0.050000000000000003,"y":0.94999999999999996},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[0,0.27586206896551724,0.55172413793103448,0.82758620689655171,1.103448275862069,1.3793103448275863,1.6551724137931034,1.9310344827586206,2.2068965517241379,2.4827586206896552,2.7586206896551726,3.0344827586206895,3.3103448275862069,3.5862068965517242,3.8620689655172411,4.1379310344827589,4.4137931034482758,4.6896551724137927,4.9655172413793105,5.2413793103448274,5.5172413793103452,5.7931034482758621,6.068965517241379,6.3448275862068968,6.6206896551724137,6.8965517241379306,7.1724137931034484,7.4482758620689653,7.7241379310344822,8],"y":[94.395243534477871,97.698225105167197,115.58708314149123,100.70508391424576,101.29287735160946,117.15064986883282,104.60916205989203,87.349387653934656,93.131471481064736,95.543380299000418,112.24081797439462,103.59813827057364,104.00771450594053,101.1068271594512,94.441588652459245,117.86913136803078,104.97850478229239,80.333828433703616,107.01355901563686,95.272085922720663,89.321762940131549,97.820250853417051,89.739955516927608,92.711087707088595,93.749607321507426,83.133066892575869,108.37787044494524,101.53373117836516,88.618630629880528,112.53814921069926],"mode":"markers","marker":{"color":"rgba(0, 100, 255, 0.7)","size":8,"line":{"color":"rgba(31,119,180,1)"}},"name":"Data points","type":"scatter","error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"line":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p class="caption">
Figure 9.6: An illustration of no correlation (<span class="math inline">\(r_{xy} \approx 0\)</span>).
</p>
</div>
<p>The interactive plot below allows us to examine the spatial arrangement of data and the resulting correlation.</p>
<center>
<iframe src="https://nishan-mudalige.shinyapps.io/Correlation_Shiny_App/?showcase=0" width="100%" height="860" data-external="1">
</iframe>
</center>
<p>Note that correlation doesn’t imply causation:</p>
<ul>
<li><p><span class="math inline">\(cor(x,y) \approx +1\)</span> doesn’t necessarily imply on increase in <span class="math inline">\(x\)</span>
causes increase in <span class="math inline">\(y\)</span>.</p></li>
<li><p><span class="math inline">\(cor(x,y) \approx -1\)</span> doesn’t necessarily imply on increase in <span class="math inline">\(x\)</span>
causes decrease in <span class="math inline">\(y\)</span>.</p></li>
</ul>
<p><strong>Properties of Covariance and Correlation</strong></p>
<p>These two values are symmetric:</p>
<ul>
<li><p><span class="math inline">\(cov(x,y) = cov(y,x)\)</span>;</p></li>
<li><p><span class="math inline">\(cor(x,y) = cor(y,x)\)</span>.</p></li>
</ul>
<div class="example">
<p><span id="exm:unlabeled-div-99" class="example"><strong>Example 9.3  </strong></span>Five observations taken for two variables follow.</p>
<div class="smalltbl">
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(x_i\)</span></th>
<th align="center"><span class="math inline">\(y_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">4</td>
<td align="center">50</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">50</td>
</tr>
<tr class="odd">
<td align="center">11</td>
<td align="center">40</td>
</tr>
<tr class="even">
<td align="center">3</td>
<td align="center">60</td>
</tr>
<tr class="odd">
<td align="center">16</td>
<td align="center">30</td>
</tr>
</tbody>
</table>
</div>
<p>Compute the sample covariance.</p>
<p>Compute and interpret the sample correlation coefficient.</p>
<p><strong>Solution:</strong></p>
<p>Step 1: Compute <span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(\bar{y}\)</span>; <span class="math inline">\(\bar{x} = 8\)</span> and
<span class="math inline">\(\bar{y} = 46\)</span> (check this by yourself).</p>
<p>Step 2: Find <span class="math inline">\(s_x\)</span> and <span class="math inline">\(s_y\)</span>.</p>
<p><span class="math display">\[s_x^2 = \frac{1}{5-1} \cdot \sum_{i = 1}^{5}(x_i - \bar{x})^2 = 29.5 \text{ and } s_y^2 = \frac{1}{5-1} \cdot \sum_{i=1}^{5}(y_i - \bar{y})^2 = 130\]</span>
Then: <span class="math inline">\(s_x = 5.4313\)</span> and <span class="math inline">\(s_y = 11.4017\)</span>.</p>
<p>Step 3: Find <span class="math inline">\(s_{xy}\)</span> and <span class="math inline">\(r\)</span>.</p>
<p><span class="math display">\[\sum_{i=1}^{5}x_i \cdot y_i = 1600, \text{ then } s_{xy} = \frac{1600}{5-1} - \frac{5\cdot8\cdot46}{5-1} = -60 \text{ and } r_{xy} = \frac{s_{xy}}{s_x \cdot s_y} = 0.9688.\]</span></p>
<p><strong>R code</strong></p>
<p>Step 1: Entering data;</p>
<div class="tcolorbox">
<pre><code>X=c(4,6,11,3,16); 

Y=c(50,50,40,60,30);</code></pre>
</div>
<p>Step 2: Finding means;</p>
<div class="tcolorbox">
<pre><code>mean(X);

mean(Y);</code></pre>
</div>
<p>Step 3: Finding variances;</p>
<div class="tcolorbox">
<pre><code>var(X);

var(Y);</code></pre>
</div>
<p>Step 4: Finding standard deviations;</p>
<div class="tcolorbox">
<pre><code>sd(X);

sd(Y):</code></pre>
</div>
<p>Step 5: Finding covariance and correlation;</p>
<div class="tcolorbox">
<pre><code>cov(X,Y);

cor(X,Y);</code></pre>
</div>
</div>
</div>
<div id="sse-ssr-and-sst" class="section level3 hasAnchor" number="9.1.4">
<h3><span class="header-section-number">9.1.4</span> SSE, SSR and SST<a href="simple-linear-regression.html#sse-ssr-and-sst" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The sum squared error (SSE), sum of squares for regression (SSR)
and the total sum of square (SST) are components of a model which are
related to the variation in the data.</p>
<p><strong>SSE (Sum of Squared Error)</strong></p>
<div class="definition">
<p><span id="def:unlabeled-div-100" class="definition"><strong>Definition 9.5  </strong></span>For any simple linear regression model, the sum of square errors SSE
measures the distance between observed data and estimated data, which is
given by:
<span class="math display">\[
\mathrm{SSE} = \sum_{i=1}^{n} (y_i - \hat{y_i})^2.
\]</span></p>
</div>
<p>The SSE is the sum of the squares of residuals (deviations predicted from
actual empirical values of data). It is a measure of the discrepancy
between the data and an estimation model.
A small SSE indicates a tight fit of the model to the data.</p>
<p>The SSE is the variation which is not explained by the model.
It is illustrated in Figure <a href="simple-linear-regression.html#fig:SSEregression">9.7</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:SSEregression"></span>
<img src="Book_Files/figure-html/SSEregression-1.png" alt="An illustration of $y_i - \hat{y}_{i}$. when these distances are squared and added together, we get the SSE." width="90%" />
<p class="caption">
Figure 9.7: An illustration of <span class="math inline">\(y_i - \hat{y}_{i}\)</span>. when these distances are squared and added together, we get the SSE.
</p>
</div>
<p><strong>SSR (Sum Square Regression)</strong></p>
<div class="definition">
<p><span id="def:unlabeled-div-101" class="definition"><strong>Definition 9.6  </strong></span>For any simple linear regression, the distance between the mean of
dependent value and estimated dependent value is called sum square
regression (SSR), which is given by
<span class="math display">\[
\mathrm{SSR} = \sum_{i=1}^{n}(\hat{y_i} - \bar{y})^2.
\]</span></p>
</div>
<p>The SSR is the variation which is explained by the model.
It measures the distance between estimated value (estimated dependent
data) and the mean of dependent data (<span class="math inline">\(\bar{y}\)</span>).
It is illustrated in Figure <a href="simple-linear-regression.html#fig:SSRregression">9.8</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:SSRregression"></span>
<img src="Book_Files/figure-html/SSRregression-1.png" alt="An illustration of $y_i - \bar{y}$. when these distances are squared and added together, we get the SSR." width="90%" />
<p class="caption">
Figure 9.8: An illustration of <span class="math inline">\(y_i - \bar{y}\)</span>. when these distances are squared and added together, we get the SSR.
</p>
</div>
<p><strong>SST (Total Sum of Squares)</strong></p>
<div class="definition">
<p><span id="def:unlabeled-div-102" class="definition"><strong>Definition 9.7  </strong></span>For any simple linear regression model, SST (Total sum of squares)
measures the sum over all squared differences between the observations
and their overall mean <span class="math inline">\(\bar{y}\)</span> is given by:
<span class="math display">\[
\mathrm{SST} = \sum_{i=1}^{n}(y_i - \bar{y})^2.
\]</span></p>
</div>
<p>The SST is the sum of the squared differences between the
observations and their overall mean <span class="math inline">\(\bar{y}\)</span> in the data.
This is illustrated in Figure <a href="simple-linear-regression.html#fig:SSTregression">9.9</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:SSTregression"></span>
<img src="Book_Files/figure-html/SSTregression-1.png" alt="An illustration of $\hat{y}_i - \bar{y}$. when these distances are squared and added together, we get the SST." width="90%" />
<p class="caption">
Figure 9.9: An illustration of <span class="math inline">\(\hat{y}_i - \bar{y}\)</span>. when these distances are squared and added together, we get the SST.
</p>
</div>
<p>The app below allows us to show or hide each of these component on one plot.</p>
<center>
<iframe src="https://nishan-mudalige.shinyapps.io/Regression_Decomposition_of_Variation/?showcase=0" width="100%" height="725" data-external="1">
</iframe>
</center>
<p><strong>Summary</strong></p>
<p>The total variation (SST) can be decomposed as the sum of the
variation explained by the model (SSR) and the variation which is not explained by the model (SSE):</p>
<p><span class="math display">\[
\begin{aligned}
SST &amp;= SSR + SSE  \\
\sum_{i=1}^{n}(y_i - \bar{y})^2 &amp;= \sum_{i=1}^{n}(\hat{y_i} - \bar{y})^2 + \sum_{i=1}^{n}(y_i - \hat{y_i})^2
\end{aligned}
\]</span>.</p>
<p><strong>Coefficient of Determination (<span class="math inline">\(r^2\)</span>)</strong></p>
<p>Moreover, we can use SST, SSE and SSR to calculate another value which
is important in simple linear regression, that is coefficient of
determination. It is proportion of variability in <span class="math inline">\(y\)</span> which is explained
by <span class="math inline">\(x\)</span>.</p>
<div class="definition">
<p><span id="def:unlabeled-div-103" class="definition"><strong>Definition 9.8  </strong></span>We define the coefficient of determination as the sum of squares due to
the regression divided by the total sum of squares.
<span class="math display">\[r^2 = \frac{SSR}{SST} = 1 - \frac{SSE}{SST}.\]</span> The coefficient of
determination can be interpreted as the proportion of the variation in
<span class="math inline">\(Y\)</span> that is explained by the regression relationship of <span class="math inline">\(Y\)</span> with <span class="math inline">\(X\)</span> (or
the proportion of the total corrected sum of squares explained by the
regression). Note that: <span class="math inline">\(0 \leq r^2 \leq 1.\)</span></p>
</div>
</div>
</div>
<div id="inference-for-simple-linear-regression" class="section level2 hasAnchor" number="9.2">
<h2><span class="header-section-number">9.2</span> Inference for Simple Linear Regression<a href="simple-linear-regression.html#inference-for-simple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In previous chapters, we focused on estimating regression parameters and
interpreting the fitted line. In this chapter, we take a step further by
conducting formal inference on the slope and intercept of a simple
linear regression model. We examine the distribution of errors, assess
variability, and introduce the idea of using hypothesis tests and
confidence intervals to evaluate whether the linear relationship
observed in the data is statistically significant.</p>
<p>We begin by introducing the regression model and exploring the
assumptions necessary to perform inference on the coefficients,
particularly the slope.</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1 X + \varepsilon, \quad \varepsilon \sim \mathcal{N}(0, \sigma^2)\]</span></p>
<p>Can perform inference on <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, however we are usually
more interested in <span class="math inline">\(\beta_1\)</span></p>
<p>What does the error term <span class="math inline">\(\varepsilon \sim \mathcal{N}(0, \sigma^2)\)</span>
mean?<br />
<strong>At each</strong> value of <span class="math inline">\(X\)</span>, the errors are distributed normally with a
mean of zero and a constant variance.</p>
<p>Can verify with residual plots (assumptions).</p>
<p>We estimate <span class="math inline">\(\sigma^2\)</span> with a value we call <span class="math inline">\(s^2\)</span> which we use for inference.</p>
<div id="estimating-variance-in-linear-regression" class="section level3 hasAnchor" number="9.2.1">
<h3><span class="header-section-number">9.2.1</span> Estimating Variance in Linear Regression<a href="simple-linear-regression.html#estimating-variance-in-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><span class="math display">\[Y = \beta_0 + \beta_1 X + \varepsilon, \quad \varepsilon \sim \mathcal{N}(0, \sigma^2)\]</span></p>
<p><strong>Estimate <span class="math inline">\(\sigma^2\)</span> with <span class="math inline">\(S^2\)</span></strong>:</p>
<p><span class="math display">\[s^2 = \frac{\sum_{i=1}^n e_i^2}{n - 2}
= \frac{\sum_{i=1}^n (y_i - \hat{y}_i)^2}{n - 2}
= \frac{SSE}{n - 2}\]</span></p>
<!-- [*notice similarity*]{style="color: red"} -->
<!-- $$S_x^2 = \frac{\sum_{i=1}^n (x_i - \bar{x})^2}{n - 1} -->
<!-- \quad {\text{(sample variance, }\bar{x} \text{ estimated)}}$$ -->
<!-- $$S = +\sqrt{S^2} -->
<!-- \quad {\text{(estimate of standard deviation)}} \\$$ -->
<p>A natural question to ask is why we divide by <span class="math inline">\(n-2\)</span> in the calculation of <span class="math inline">\(s^2\)</span>.
The reason is that we are estimating 2 unknown parameters in the model (both <span class="math inline">\(\beta_0\)</span> and
<span class="math inline">\(\beta_1\)</span> are unknown) and since the calculation of <span class="math inline">\(s^2\)</span> uses estimates of both parameters, we lose 2 degrees of freedom.</p>
<div class="remark">
<p><span id="unlabeled-div-104" class="remark"><em>Remark</em>. </span>We can use <span class="math inline">\(s{x}, \, s{y}, \, \bar{x}, \, \bar{y}\)</span> and <span class="math inline">\(r\)</span> to calculate the least square estimators using</p>
<p><span class="math display">\[
\begin{aligned}
\hat{\beta}_1 &amp; = r \frac{s_y}{s_x} \\
\text{and}  \\
\hat{\beta}_0 &amp; = \bar{y} - \hat{\beta}_1 \bar{x}
\end{aligned}
\]</span></p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-105" class="example"><strong>Example 9.4  </strong></span>Suppose an appliance store conducts a 5-month experiment to determine
the effect of advertising on sales revenue. The results are shown in a
table below. The relationship between sales revenue, <span class="math inline">\(y\)</span>, and
advertising expenditure, <span class="math inline">\(x\)</span>, is hypothesized to follow a first-order
linear model, that is,</p>
<p><span class="math display">\[y = \beta_0 + \beta_1 x + \varepsilon\]</span></p>
<p>where</p>
<p><span class="math display">\[\begin{aligned}
y &amp; = \text{dependent variable} \\
x &amp; = \text{independent variable} \\
\beta_0 &amp; = \text{$y$-intercept} \\
\beta_1 &amp; = \text{slope of the line} \\
\varepsilon &amp; = \text{error variable}
\end{aligned}\]</span></p>
<table>
<thead>
<tr class="header">
<th>Month</th>
<th>Expenditure <span class="math inline">\(x\)</span> (hundreds)</th>
<th>Revenue <span class="math inline">\(y\)</span> (thousands)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>2</td>
<td>2</td>
<td>1</td>
</tr>
<tr class="odd">
<td>3</td>
<td>3</td>
<td>2</td>
</tr>
<tr class="even">
<td>4</td>
<td>4</td>
<td>2</td>
</tr>
<tr class="odd">
<td>5</td>
<td>5</td>
<td>4</td>
</tr>
</tbody>
</table>
<p>The question is how can we best use the information in the sample
of five observations in our table to estimate the unknown <span class="math inline">\(y\)</span>-intercept
<span class="math inline">\(\beta_0\)</span> and slope <span class="math inline">\(\beta_1\)</span>?</p>
<p>We are given:
<span class="math display">\[\bar{x} = 3, \quad \bar{y} = 2, \quad S_x = 1.5811, \quad S_y = 1.2247, \quad S_{xy} = 1.75\]</span></p>
<p>Then, the slope of the least squares line is</p>
<p><span class="math display">\[b_1 = r \frac{S_y}{S_x} = (0.9037) \left( \frac{1.2247}{1.5811} \right) = 0.7\]</span></p>
<p>and</p>
<p><span class="math display">\[b_0 = \bar{y} - b_1 \bar{x} = 2 - (0.7)(3) = -0.1\]</span></p>
<p>The least squares line is thus:</p>
<p><span class="math display">\[\hat{y} = -0.1 + 0.7x\]</span></p>
</div>
</div>
<div id="confidence-intervals-and-hypothesis-tests" class="section level3 hasAnchor" number="9.2.2">
<h3><span class="header-section-number">9.2.2</span> Confidence Intervals and Hypothesis Tests<a href="simple-linear-regression.html#confidence-intervals-and-hypothesis-tests" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We have <span class="math inline">\(n\)</span> observations on an explanatory variable <span class="math inline">\(x\)</span> and a response
variable <span class="math inline">\(y\)</span>. Our goal is to study or predict the behavior of <span class="math inline">\(y\)</span> for
given values of <span class="math inline">\(x\)</span>.</p>
<ul>
<li><p>For any fixed value of <span class="math inline">\(x\)</span>, the response <span class="math inline">\(y\)</span> varies according to a
Normal distribution. Repeated measures <span class="math inline">\(y\)</span> are independent of each
other.</p></li>
<li><p>The mean response <span class="math inline">\(\mu_y\)</span> has a straight-line relationship with <span class="math inline">\(x\)</span>:
<span class="math inline">\(\mu_y = \beta_0 + \beta_1 x\)</span>. The slope <span class="math inline">\(\beta_1\)</span> and intercept
<span class="math inline">\(\beta_0\)</span> are <strong>unknown</strong> parameters.</p></li>
<li><p>The standard deviation of <span class="math inline">\(y\)</span> (call it <span class="math inline">\(\sigma\)</span>) is the same for all
values of <span class="math inline">\(x\)</span>. The value of <span class="math inline">\(\sigma\)</span> is <strong>unknown</strong>. The regression
model has three parameters, <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, and <span class="math inline">\(\sigma\)</span>.</p></li>
</ul>
<p>Thus, if <span class="math display">\[\hat{y}_i = \hat{\beta}_0 + \hat{\beta}_1 x_i\]</span> is the
predicted value of the <span class="math inline">\(i\)</span>th <span class="math inline">\(y\)</span> value, then the deviation of the
observed value <span class="math inline">\(y_i\)</span> from <span class="math inline">\(\hat{y}_i\)</span> is the difference
<span class="math inline">\(y_i - \hat{y}_i\)</span> and the sum of squares of deviations to be minimized
is</p>
<p><span class="math display">\[SSE = \sum_{i=1}^{n} (y_i - \hat{y}_i)^2 = \sum_{i=1}^{n} [y_i - (\hat{\beta}_0 + \hat{\beta}_1 x_i)]^2.\]</span></p>
<p>The quantity <em>SSE</em> is also called the <strong>sum of squares for error</strong>.
<span class="math display">\[\begin{aligned}
\text{Fitted Value:} \quad &amp; \hat{y}_i = \hat{\beta}_0 + \hat{\beta}_1 x_i \\
\text{Residual:} \quad &amp; \hat{\varepsilon}_i = y_i - \hat{y}_i
\end{aligned}\]</span></p>
<p>The <strong>regression standard error</strong> is</p>
<p><span class="math display">\[s = \sqrt{\frac{1}{n - 2} \sum \text{residual}^2}
= \sqrt{\frac{1}{n - 2} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2}
= \sqrt{\frac{SSE}{n - 2}}\]</span></p>
<p>Use <span class="math inline">\(s\)</span> to estimate the <strong>unknown</strong> <span class="math inline">\(\sigma\)</span> in the regression model</p>
<p>The standard error of <span class="math inline">\(\hat{\beta}_1\)</span> is the standard deviation of the
sampling distribution of <span class="math inline">\(\hat{\beta}_1\)</span> (estimate of slope <span class="math inline">\(\beta_1\)</span>):</p>
<p><span class="math display">\[SE(\hat{\beta}_1) = \frac{s}{\sqrt{\sum_{i=1}^{n} (x_i - \bar{x})^2}}
= \frac{s}{\sqrt{(n - 1) s_x^2}}\]</span></p>
<p><strong>Confidence Interval for the Slope</strong></p>
<p><span class="math display">\[\hat{\beta}_1 \pm t_{(n-2, \, \alpha/2)} \cdot SE(\hat{\beta}_1)
\quad = \quad
\hat{\beta}_1 \pm t_{(n-2, \, \alpha/2)} \cdot \frac{s}{\sqrt{\sum_{i=1}^{n} (x_i - \bar{x})^2}}\]</span></p>
<div class="example">
<p><span id="exm:unlabeled-div-106" class="example"><strong>Example 9.5  </strong></span>Revisit the example on advertising and sales and construct a 95%
confidence interval on the slope. Provide an interpretation of the CI.</p>
<p>From earlier: <span class="math display">\[\hat{y} = -0.1 + 0.7x\]</span></p>
<div class="center">
<table>
<thead>
<tr class="header">
<th align="center"><strong><span class="math inline">\(x\)</span></strong></th>
<th align="center"><strong><span class="math inline">\(y\)</span></strong></th>
<th align="center"><strong><span class="math inline">\(\hat{y}\)</span></strong></th>
<th align="center"><strong><span class="math inline">\(y - \hat{y}\)</span></strong></th>
<th align="center"><strong><span class="math inline">\((y - \hat{y})^2\)</span></strong></th>
<th align="center"><strong><span class="math inline">\((x - \bar{x})^2\)</span></strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">1</td>
<td align="center">0.6</td>
<td align="center">0.4</td>
<td align="center">0.16</td>
<td align="center">4</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">1</td>
<td align="center">1.3</td>
<td align="center">-0.3</td>
<td align="center">0.09</td>
<td align="center">1</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">2</td>
<td align="center">2.0</td>
<td align="center">0.0</td>
<td align="center">0.00</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">2</td>
<td align="center">2.7</td>
<td align="center">-0.7</td>
<td align="center">0.49</td>
<td align="center">1</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">4</td>
<td align="center">3.4</td>
<td align="center">0.6</td>
<td align="center">0.36</td>
<td align="center">4</td>
</tr>
</tbody>
</table>
</div>
<p>We are given:
<span class="math display">\[\sum x_i = 15, \quad \bar{x} = \frac{15}{5} = 3, \quad SSE = 1.10, \quad \sum (x_i - \bar{x})^2 = 10\]</span></p>
<p><strong>Step 1: Estimate variance and standard deviation</strong>
<span class="math display">\[s^2 = \frac{SSE}{n-2} = \frac{1.10}{5 - 2} = 0.3667
\quad \Rightarrow \quad
s = \sqrt{0.3667} = 0.6055\]</span></p>
<p><strong>Step 2: Compute standard error of <span class="math inline">\(\hat{\beta}_1\)</span></strong>
<span class="math display">\[SE(\hat{\beta}_1) = \frac{s}{\sqrt{\sum (x_i - \bar{x})^2}}
= \frac{0.6055}{\sqrt{10}} = 0.1914\]</span></p>
<p><strong>Step 3: Determine critical <span class="math inline">\(t\)</span>-value</strong></p>
<p><span class="math display">\[n - 2 = 3, \quad \alpha = 0.05, \quad \alpha/2 = 0.025
\Rightarrow \quad
t_{(3, 0.025)} = 3.182\]</span></p>
<p><strong>Step 4: Construct CI for the slope</strong>
<span class="math display">\[\hat{\beta}_1 \pm t_{(n-2, \alpha/2)} \cdot SE(\hat{\beta}_1)
= 0.7 \pm 3.182 \cdot 0.1914 = 0.7 \pm 0.6092\]</span></p>
<p><span class="math display">\[\Rightarrow \text{CI: } (0.0908, \; 1.3092)\]</span></p>
<p><strong>Interpretation:</strong> We are 95% confident the slope (<span class="math inline">\(\beta_1\)</span>) for this
model lies between 0.0908 and 1.3092.</p>
</div>
<!-- ### Interpreting Confidence Intervals for $\beta_1$ {#interpreting-confidence-intervals-for-beta_1 .unnumbered} -->
<div class="center">
<table style="width:97%;">
<colgroup>
<col width="22%" />
<col width="74%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="right"><strong>Suppose CI:</strong></td>
<td align="left"><span class="math inline">\((-, -)\)</span>
Suggests <span class="math inline">\(\beta_1\)</span> has a <strong>negative</strong> sign.
Suggests negative correlation, potentially good model.</td>
</tr>
<tr class="even">
<td align="right"><strong>Suppose CI:</strong></td>
<td align="left"><span class="math inline">\((+, +)\)</span>
Suggests <span class="math inline">\(\beta_1\)</span> has a <strong>positive</strong> sign.
Suggests positive correlation, potentially good model.</td>
</tr>
<tr class="odd">
<td align="right"><strong>Suppose CI:</strong></td>
<td align="left"><span class="math inline">\((-, +)\)</span>
<span class="math inline">\(\beta_1 = 0\)</span> is plausible.
Suggests <strong>no linear relationship</strong> between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</td>
</tr>
</tbody>
</table>
</div>
<p>In cases where the CI does not contain zero, we can infer the sign of
the slope (just not the steepness)</p>
<p>The <strong>regression standard error</strong> is</p>
<p><span class="math display">\[s = \sqrt{\frac{1}{n - 2} \sum_{i=1}^n (y_i - \hat{y}_i)^2} = \sqrt{\frac{SSE}{n - 2}} = \sqrt{\frac{1.1}{3}} = 0.6055\]</span></p>
<p>Use <span class="math inline">\(s\)</span> to estimate the <strong>unknown</strong> <span class="math inline">\(\sigma\)</span> in the regression model</p>
<p>A level <span class="math inline">\(C\)</span> confidence interval for the slope <span class="math inline">\(\beta_1\)</span> of the true
regression line is</p>
<p><span class="math display">\[\hat{\beta}_1 \pm t^* SE(\hat{\beta}_1)\]</span></p>
<p>In this formula, the standard error of the least-squares slope <span class="math inline">\(\beta_{1}\)</span> is</p>
<p><span class="math display">\[SE(\hat{\beta}_1) = \frac{s}{\sqrt{\sum (x_i - \bar{x})^2}} = \frac{s}{\sqrt{(n - 1) SS_{xx} }}\]</span></p>
<p>and <span class="math inline">\(t^*\)</span> is the critical value for the <span class="math inline">\(t(n - 2)\)</span> density curve with
area <span class="math inline">\(C\)</span> between <span class="math inline">\(-t^*\)</span> and <span class="math inline">\(t^*\)</span>.</p>
<div class="tcolorbox">
<p><strong>Hypotheses:</strong> <span class="math display">\[\begin{aligned}
H_0\!: \beta_1 = 0 \quad &amp; \text{vs.} \quad H_a\!: \beta_1 &gt; 0 \\
H_0\!: \beta_1 = 0 \quad &amp; \text{vs.} \quad H_a\!: \beta_1 &lt; 0 \\
H_0\!: \beta_1 = 0 \quad &amp; \text{vs.} \quad H_a\!: \beta_1 \neq 0 \quad \text{\textit{(most common)}}
\end{aligned}\]</span></p>
<p><strong>Test Statistic:</strong>
<span class="math display">\[t = \frac{\hat{\beta}_1 - 0}{SE(\hat{\beta}_1)} = \frac{\hat{\beta}_1}{\dfrac{s}{\sqrt{\sum_{i=1}^n (x_i - \bar{x})^2}}}\]</span></p>
<p><strong>Reference distribution:</strong> <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n - 2\)</span> degrees of
freedom.</p>
<p><em>Note:</em> A test statistic always follows the form:
<span class="math display">\[\text{test stat} = \frac{\text{statistic} - \text{hypothesized value}}{\text{SE(statistic)}}\]</span></p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-107" class="example"><strong>Example 9.6  </strong></span>For the advertising example, perform a two-sided hypothesis test on the
slope.</p>
<p><strong>Hypotheses:</strong> <span class="math display">\[H_0\!: \beta_1 = 0
\qquad
H_a\!: \beta_1 \neq 0\]</span></p>
<p><strong>Test Statistic:</strong>
<span class="math display">\[t^* = \frac{\hat{\beta}_1 - 0}{\dfrac{s}{\sqrt{\sum (x_i - \bar{x})^2}}}
= \frac{0.7 - 0}{0.6055 / \sqrt{10}} = 3.6558\]</span></p>
<p><strong>Reference Distribution:</strong> <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n - 2 = 5 - 2 = 3\)</span>
degrees of freedom.</p>
<p><strong>Decision Rule:</strong></p>
<p>Using a two-tailed test:
<span class="math display">\[\text{p-value} = 2 \cdot P(T_3 &gt; 3.6558) &lt; 0.01 \Rightarrow \text{p-value} &lt; 0.05\]</span></p>
<p><strong>Conclusion:</strong> Since <span class="math inline">\(p\)</span>-value <span class="math inline">\(&lt; 0.05\)</span>, we reject <span class="math inline">\(H_0\)</span> and conclude
<span class="math inline">\(H_a\!: \beta_1 \neq 0\)</span>.</p>
<p><em>Interpretation:</em> The slope should be included in the model. There is
significant evidence of a linear relationship between advertising and
sales revenue</p>
<p>For the advertising-sales example, a 95% Confidence Interval for the
slope <span class="math inline">\(\beta_1\)</span> is
<span class="math display">\[0.7 \pm 3.182 \left( \frac{0.6055}{\sqrt{10}} \right)\]</span>
<span class="math display">\[0.7 \pm 0.6092\]</span></p>
<p>Thus, we estimate with 95% confidence that the interval from 0.0908 and
1.3092 includes the parameter <span class="math inline">\(\beta_1\)</span>.</p>
</div>
<p>We can also test hypotheses about the slope <span class="math inline">\(\beta_1\)</span>. The most common
hypothesis is</p>
<p><span class="math display">\[H_0 : \beta_1 = 0.\]</span></p>
<p>A regression line with slope 0 is horizontal. That is, the mean of <span class="math inline">\(y\)</span>
does not change at all when <span class="math inline">\(x\)</span> changes. So this <span class="math inline">\(H_0\)</span> says that there
is no true linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</p>
<div class="tcolorbox">
<p>To test the hypothesis <span class="math inline">\(H_0 : \beta_1 = 0\)</span>, compute the <span class="math inline">\(t\)</span> statistic
<span class="math display">\[t = \frac{\hat{\beta}_1}{SE({\hat{\beta}_1})}.\]</span></p>
<p>In terms of a random variable <span class="math inline">\(T\)</span> having the <span class="math inline">\(t(n - 2)\)</span> distribution,
the P-value for a test of <span class="math inline">\(H_0\)</span> against: <span class="math display">\[\begin{aligned}
H_a : \beta_1 \ne 0 &amp; \quad \text{is } 2P(T &gt; |t|). \\
H_a : \beta_1 &gt; 0 &amp; \quad \text{is } P(T &gt; t). \\
H_a : \beta_1 &lt; 0 &amp; \quad \text{is } P(T &lt; t).
\end{aligned}\]</span></p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-108" class="example"><strong>Example 9.7  </strong></span><span class="math display">\[\alpha = 0.05\]</span></p>
<ol style="list-style-type: decimal">
<li><p><span class="math inline">\(H_0: \beta_1 = 0 \quad \text{vs} \quad H_a: \beta_1 &gt; 0\)</span></p></li>
<li><p><span class="math inline">\(t^* = \displaystyle\frac{\hat{\beta}_1}{SE(\hat{\beta}_1)} = \displaystyle\frac{0.7}{0.1914} = 3.6572\)</span></p></li>
<li><p><span class="math inline">\(P\text{-value} = P(T &gt; t) = P(T &gt; 3.6572) \quad \text{d.f.} = n - 2 = 5 - 2 = 3.\)</span><br />
Using t-distribution table, <span class="math inline">\(0.01 &lt; P\text{ value} &lt; 0.025\)</span></p></li>
<li><p>Since <span class="math inline">\(P\text{-value} &lt; \alpha = 0.05\)</span>, we reject <span class="math inline">\(H_0\)</span>.</p></li>
</ol>
<p>Our example (different <span class="math inline">\(H_a\)</span>) <span class="math display">\[\alpha = 0.05\]</span></p>
<ol style="list-style-type: decimal">
<li><p><span class="math inline">\(H_0: \beta_1 = 0 \quad \text{vs} \quad H_a: \beta_1 \neq 0\)</span></p></li>
<li><p><span class="math inline">\(t^* = \frac{b_1}{SE_{b_1}} = \frac{0.7}{0.1914} = 3.6572\)</span></p></li>
<li><p><span class="math inline">\(P\text{-value} = 2P(T &gt; |t|) = 2P(T &gt; 3.6572) \quad \text{d.f.} = n - 2 = 5 - 2 = 3.\)</span><br />
Using Table 3, <span class="math inline">\(0.02 &lt; P\text{ value} &lt; 0.05\)</span></p></li>
<li><p>Since <span class="math inline">\(P\text{-value} &lt; \alpha = 0.05\)</span>, we reject <span class="math inline">\(H_0\)</span>.</p></li>
</ol>
<p><strong>R code</strong></p>
<div class="tcolorbox">
<pre><code>x = c(1, 2, 3, 4, 5);
y = c(1, 1, 2, 2, 4);
mod = lm(y~x);
summary(mod);</code></pre>
</div>
<p><strong>R Output</strong></p>
<div class="tcolorbox">
<pre><code>## 
## Call:
## lm(formula = y~x)
## 
## Residuals:
##       1        2        3        4        5 
##  4.000e-01 -3.000e-01 -3.886e-16 -7.000e-01  6.000e-01 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)  -0.1000     0.6351  -0.157  0.8849    
## x             0.7000     0.1915   3.656  0.0354 *  
## ---
## Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
## 
## Residual standard error: 0.6055 on 3 degrees of freedom</code></pre>
</div>
<p><span class="math display">\[\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x = -0.10 + 0.70x\]</span>
<span class="math display">\[SE(\hat{\beta}_1) = 0.1915\]</span></p>
<p>By default, R conducts the following test for each coefficient:</p>
<p><span class="math display">\[\begin{aligned}
    H_0&amp;: \beta_j = 0 \\
    H_a&amp;: \beta_j \ne 0 \quad \text{(two sided)}
\end{aligned}\]</span></p>
<p>Test statistic: <span class="math display">\[t^* = \frac{\hat{\beta}_j - 0}{SE(\hat{\beta}_j)}\]</span></p>
<p>For advertising and sales data: <span class="math display">\[\begin{aligned}
    H_0&amp;: \beta_1 = 0 \\
    H_a&amp;: \beta_1 \ne 0
\end{aligned}\]</span></p>
<p><span class="math display">\[t^* = \frac{\hat{\beta}_1 - 0}{SE(\hat{\beta}_1)} = \frac{0.70}{0.1915} = 3.656\]</span></p>
</div>
<div class="nt">
<p><strong>Review</strong></p>
<p><span class="math display">\[\begin{aligned}
y &amp;= \beta_0 + \beta_1 x + \varepsilon, \quad \varepsilon \sim N(0, \sigma^2) \\
\hat{y} &amp;= \hat{\beta}_0 + \hat{\beta}_1 x \\
\hat{\beta}_1 &amp;= \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{\sum (x_i - \bar{x})^2} = \frac{s_{xy}}{s_{xx}} \\
\hat{\beta}_0 &amp;= \bar{y} - \hat{\beta}_1 \bar{x} \\
\end{aligned}\]</span></p>
<p><strong>r:</strong> coefficient of correlation (strength)<br />
<strong>r<span class="math inline">\(^2\)</span>:</strong> coefficient of determination (% variability)</p>
<p><span class="math display">\[\begin{aligned}
s^2 &amp;= \frac{\sum_{i=1}^n (y_i - \hat{y}_i)^2}{n - 2} = \frac{SSE}{n - 2} \\
s &amp;= \sqrt{s^2} \\
SE(\hat{\beta}_1) &amp;= \frac{s}{\sqrt{s_{xx}}} \\
CI &amp;: \hat{\beta}_1 \pm t_{n - 2, \alpha/2} \cdot SE(\hat{\beta}_1) \\
\end{aligned}\]</span> Hypothesis test: <span class="math display">\[\begin{aligned}
H_0 &amp;: \beta_1 = 0 \\
\text{Test stat:}\quad t &amp;= \frac{\hat{\beta}_1 - 0}{SE(\hat{\beta}_1)}
\end{aligned}\]</span></p>
</div>
<p>We square all three deviations for each one of our data points, and sum
over all <span class="math inline">\(n\)</span> points. Here, cross terms drop out, and we are left with
the following equation:</p>
<p><span class="math display">\[\sum_{i=1}^{n}(y_i - \bar{y})^2 = \sum_{i=1}^{n}(y_i - \hat{y}_i)^2 + \sum_{i=1}^{n}(\hat{y}_i - \bar{y})^2\]</span></p>
<p><span class="math display">\[\text{SST} = \text{SSE} + \text{SSR}\]</span></p>
<p>Total sum of squares = Sum of squares for error + Sum of squares for
regression</p>
<p><span class="math display">\[\begin{aligned}
SSE &amp;= \sum_{i=1}^{n} (y_i - \hat{y}_i)^2 \\
    &amp;= \sum_{i=1}^{n} (y_i - \bar{y})^2 - \hat{\beta}_1 \sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y}) \\
    &amp;= S_{YY} - \hat{\beta}_1 S_{XY}
\end{aligned}\]</span></p>
<p>Notice that this provides an easier computational method of finding
SSE</p>
<p><strong>R output (Additional example)</strong></p>
<div class="tcolorbox">
<pre><code>&gt; summary(model);

Call:
lm(formula = camrys$Price ~ Odometer, data = camrys)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.68679 -0.27263  0.00521  0.23210  0.70071 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  17.248727   0.182093   94.72   &lt;2e-16 ***
Odometer     -0.066861   0.004975  -13.44   &lt;2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.3265 on 98 degrees of freedom
Multiple R-squared:  0.6483,    Adjusted R-squared:  0.6447 
F-statistic: 180.6 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div id="anova-table-for-simple-linear-regression" class="section level3 hasAnchor" number="9.2.3">
<h3><span class="header-section-number">9.2.3</span> ANOVA Table for Simple Linear Regression<a href="simple-linear-regression.html#anova-table-for-simple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Analysis of Variance (ANOVA) is a statistical method used to assess
whether variation in a response variable can be explained by predictor
variables in a regression model. It summarizes sources of variation
using sums of squares, degrees of freedom, and mean squares in a
structured table format.</p>
<table>
<thead>
<tr class="header">
<th align="left"><strong>Source of Variation</strong></th>
<th align="center"><strong>Sum of Squares</strong></th>
<th align="center"><strong>Degrees of Freedom</strong></th>
<th align="center"><strong>Mean Square</strong></th>
<th align="center"><strong>Computed F</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Regression</td>
<td align="center">SSR</td>
<td align="center">1</td>
<td align="center">SSR</td>
<td align="center"><span class="math inline">\(\dfrac{SSR}{SSE / (n - 2)}\)</span></td>
</tr>
<tr class="even">
<td align="left">Error</td>
<td align="center">SSE</td>
<td align="center"><span class="math inline">\(n - 2\)</span></td>
<td align="center"><span class="math inline">\(s^2 = \dfrac{SSE}{n - 2}\)</span></td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="left">Total</td>
<td align="center">SST</td>
<td align="center"><span class="math inline">\(n - 1\)</span></td>
<td align="center"></td>
<td align="center"></td>
</tr>
</tbody>
</table>
<p>For the general multivariate regression model: <span class="math display">\[\begin{aligned}
    Y &amp;= \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_p X_p + \varepsilon, \\
      &amp;\quad \varepsilon \sim N(0, \sigma^2)
\end{aligned}\]</span> with <span class="math inline">\(p\)</span> predictors</p>
<p>ANOVA can be used for testing: <span class="math display">\[\begin{aligned}
    H_0&amp;: \beta_1 = \beta_2 = \cdots = \beta_p = 0 \\
    H_a&amp;: \text{At least one } \beta_j \ne 0, \quad j = 1, \ldots, p
\end{aligned}\]</span></p>
<p><strong>Test Statistic:</strong> <span class="math display">\[\begin{aligned}
    F &amp;= \dfrac{MSR}{MSE} = \dfrac{SSR/p}{SSE / (n - p - 1)} \sim F(p, n - p - 1)
\end{aligned}\]</span></p>
<p><strong>Reference distribution:</strong> <span class="math inline">\(F\)</span> with numerator df = <span class="math inline">\(p\)</span>, denominator df
= <span class="math inline">\(n - p - 1\)</span></p>
<div class="example">
<p><span id="exm:unlabeled-div-109" class="example"><strong>Example 9.8  </strong></span>We fitted a simple linear regression model using:</p>
<div class="tcolorbox">
<pre><code>x = c(1,2,3,4,5);
y = c(1,1,2,2,4);
mod = lm(y~x);
anova(mod);</code></pre>
</div>
<p>The ANOVA output was:</p>
<div class="tcolorbox">
<pre><code>## Analysis of Variance Table
##
## Response: y
##             Df  Sum Sq Mean Sq F value   Pr(&gt;F)
## x            1     4.9    4.9000  13.364  0.03535 *
## Residuals    3     1.1    0.3667
## ---
## Signif. codes:
## 0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
</div>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p>The regression model includes one predictor <span class="math inline">\(x\)</span>, so the degrees of
freedom for regression is 1.</p></li>
<li><p>The sum of squares for regression is <span class="math inline">\(SSR = 4.9\)</span>, and for residuals
<span class="math inline">\(SSE = 1.1\)</span>.</p></li>
<li><p>Mean squares are calculated as:
<span class="math display">\[MSR = \frac{SSR}{1} = 4.9, \quad MSE = \frac{SSE}{n - 2} = \frac{1.1}{3} = 0.3667\]</span></p></li>
<li><p>The F-statistic is:
<span class="math display">\[F = \frac{MSR}{MSE} = \frac{4.9}{0.3667} \approx 13.364\]</span></p></li>
<li><p>The p-value is <span class="math inline">\(\approx 0.03535\)</span>, indicating that the predictor is
significant at the 5% level.</p></li>
</ul>
<p><strong>Conclusion:</strong> Since the p-value is less than 0.05, we reject <span class="math inline">\(H_0\)</span> and
conclude that <span class="math inline">\(x\)</span> has a statistically significant linear relationship
with <span class="math inline">\(y\)</span>.</p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-110" class="example"><strong>Example 9.9  </strong></span>We consider data on apartments near UTM, with price (in thousands of
dollars), area (in 100 square feet), and number of beds and baths.</p>
<div class="center">
<table>
<tbody>
<tr class="odd">
<td align="center"><strong>Price</strong></td>
<td align="center"><strong>Area</strong></td>
<td align="center"><strong>Beds</strong></td>
<td align="center"><strong>Baths</strong></td>
</tr>
<tr class="even">
<td align="center">(<span class="math inline">\(\times 1000\)</span>)</td>
<td align="center">(<span class="math inline">\(\times 100\)</span> sq ft)</td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center">620</td>
<td align="center">11.0</td>
<td align="center">2</td>
<td align="center">2</td>
</tr>
<tr class="even">
<td align="center">590</td>
<td align="center">6.5</td>
<td align="center">2</td>
<td align="center">1</td>
</tr>
<tr class="odd">
<td align="center">620</td>
<td align="center">10.0</td>
<td align="center">2</td>
<td align="center">2</td>
</tr>
<tr class="even">
<td align="center">700</td>
<td align="center">8.4</td>
<td align="center">2</td>
<td align="center">2</td>
</tr>
<tr class="odd">
<td align="center">680</td>
<td align="center">8.0</td>
<td align="center">2</td>
<td align="center">2</td>
</tr>
<tr class="even">
<td align="center">500</td>
<td align="center">5.7</td>
<td align="center">1</td>
<td align="center">1</td>
</tr>
<tr class="odd">
<td align="center">760</td>
<td align="center">12.0</td>
<td align="center">2</td>
<td align="center">2</td>
</tr>
<tr class="even">
<td align="center">800</td>
<td align="center">14.0</td>
<td align="center">3</td>
<td align="center">1</td>
</tr>
<tr class="odd">
<td align="center">660</td>
<td align="center">7.3</td>
<td align="center">2</td>
<td align="center">1</td>
</tr>
</tbody>
</table>
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-30"></span>
<img src="Book_Files/figure-html/unnamed-chunk-30-1.png" alt="Plot of Price vs Area for Apartments near UTM" width="80%" />
<p class="caption">
Figure 9.10: Plot of Price vs Area for Apartments near UTM
</p>
</div>
<table>
<caption>Deviation table for computing <span class="math inline">\(\hat{\beta}_1\)</span> and <span class="math inline">\(\hat{\beta}_0\)</span>.</caption>
<colgroup>
<col width="6%" />
<col width="5%" />
<col width="17%" />
<col width="17%" />
<col width="33%" />
<col width="20%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Price</th>
<th align="right">Area</th>
<th align="right"><span class="math inline">\((x-\bar{x})\)</span></th>
<th align="right"><span class="math inline">\((y-\bar{y})\)</span></th>
<th align="right"><span class="math inline">\((x-\bar{x})(y-\bar{y})\)</span></th>
<th align="right"><span class="math inline">\((x-\bar{x})^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">620</td>
<td align="right">11.0</td>
<td align="right">1.8</td>
<td align="right">-38.9</td>
<td align="right">-70.02</td>
<td align="right">3.24</td>
</tr>
<tr class="even">
<td align="right">590</td>
<td align="right">6.5</td>
<td align="right">-2.7</td>
<td align="right">-68.9</td>
<td align="right">186.03</td>
<td align="right">7.29</td>
</tr>
<tr class="odd">
<td align="right">620</td>
<td align="right">10.0</td>
<td align="right">0.8</td>
<td align="right">-38.9</td>
<td align="right">-31.12</td>
<td align="right">0.64</td>
</tr>
<tr class="even">
<td align="right">700</td>
<td align="right">8.4</td>
<td align="right">-0.8</td>
<td align="right">41.1</td>
<td align="right">-32.88</td>
<td align="right">0.64</td>
</tr>
<tr class="odd">
<td align="right">680</td>
<td align="right">8.0</td>
<td align="right">-1.2</td>
<td align="right">21.1</td>
<td align="right">-25.32</td>
<td align="right">1.44</td>
</tr>
<tr class="even">
<td align="right">500</td>
<td align="right">5.7</td>
<td align="right">-3.5</td>
<td align="right">-158.9</td>
<td align="right">556.15</td>
<td align="right">12.25</td>
</tr>
<tr class="odd">
<td align="right">760</td>
<td align="right">12.0</td>
<td align="right">2.8</td>
<td align="right">101.1</td>
<td align="right">283.08</td>
<td align="right">7.84</td>
</tr>
<tr class="even">
<td align="right">800</td>
<td align="right">14.0</td>
<td align="right">4.8</td>
<td align="right">141.1</td>
<td align="right">677.28</td>
<td align="right">23.04</td>
</tr>
<tr class="odd">
<td align="right">660</td>
<td align="right">7.3</td>
<td align="right">-1.9</td>
<td align="right">1.1</td>
<td align="right">-2.09</td>
<td align="right">3.61</td>
</tr>
<tr class="even">
<td align="right"><strong>Sum</strong></td>
<td align="right">82.9</td>
<td align="right"></td>
<td align="right"></td>
<td align="right"><span class="math inline">\(\sum (x - \bar{x})(y - \bar{y})\)</span></td>
<td align="right"><span class="math inline">\(\sum (x - \bar{x})^2\)</span></td>
</tr>
<tr class="odd">
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right">= 1541.11</td>
<td align="right">= 60.00</td>
<td align="right"></td>
</tr>
</tbody>
</table>
<p>The sample means are:
<span class="math display">\[
\begin{aligned}
\bar{y} &amp;= \frac{\sum y}{n} = \frac{5930}{9} = 658.89\\
\hfill\\
\bar{x} &amp;= \frac{\sum x}{n} = \frac{82.9}{9} = 9.21
\end{aligned}
\]</span></p>
<div id="finding-the-regression-coefficients" class="section level4 unnumbered hasAnchor">
<h4>Finding the Regression Coefficients<a href="simple-linear-regression.html#finding-the-regression-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To compute the least squares regression line, we calculate the slope and
intercept using the formulas:</p>
<p><span class="math display">\[
\begin{aligned}
\hat{\beta}_1 &amp;= \frac{S_{xy}}{S_{xx}} = \frac{1541.11}{60} = 25.69 \\
\hfill\\
\hat{\beta}_0 &amp;= \bar{y} - \hat{\beta}_1 \bar{x} = 658.89 - (25.69)(9.21) = 422.28
\end{aligned}
\]</span></p>
</div>
<div id="equation-of-the-regression-line" class="section level4 unnumbered hasAnchor">
<h4>Equation of the Regression Line<a href="simple-linear-regression.html#equation-of-the-regression-line" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Using the values above, we write the estimated regression equation as:</p>
<p><span class="math display">\[\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x = 422.28 + 25.69x\]</span></p>
<p>This equation gives the predicted apartment price (in $1000s) based on
area (in 100 sq ft).</p>
</div>
<div id="interpretation-of-coefficients" class="section level4 unnumbered hasAnchor">
<h4>Interpretation of Coefficients<a href="simple-linear-regression.html#interpretation-of-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The slope <span class="math inline">\(\hat{\beta}_1 = 25.69\)</span> means that for every additional 100 sq
ft in area, we expect the apartment price to increase by approximately
$25,690 on average</p>
<p>The intercept <span class="math inline">\(\hat{\beta}_0 = 422.28\)</span> suggests the predicted price when
the area is zero. While this has no practical interpretation in this
context, it is a necessary component of the regression model.</p>
</div>
<div id="interpolation-and-extrapolation" class="section level4 unnumbered hasAnchor">
<h4>Interpolation and Extrapolation<a href="simple-linear-regression.html#interpolation-and-extrapolation" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To estimate the price of an apartment with an area of 800 sq ft (i.e.,
<span class="math inline">\(x = 8\)</span>), we compute:</p>
<p><span class="math display">\[\hat{y} = 422.28 + 25.69(8) = 627.8 \quad (\$1000)\]</span></p>
<p>Since 8 is within the range of observed values, this is an example of
<strong>interpolation.</strong></p>
<p>For an apartment with 2,500 sq ft (<span class="math inline">\(x = 25\)</span>):</p>
<p><span class="math display">\[\hat{y} = 422.28 + 25.69(25) = 1064.53 \quad (\$1000)\]</span></p>
<p>This is an example of <strong>extrapolation</strong>, and such predictions should be
treated with caution since they lie outside the data range</p>
<p>We can create a simple linear regression model in R using the <code>lm</code>
command:</p>
<p><strong>R code</strong></p>
<div class="tcolorbox">
<pre><code>lm(y ~ x, data = data_source)</code></pre>
</div>
<p>The data is available in the <code>apt_around_utm.csv</code> file.</p>
<p><strong>R code</strong></p>
<div class="tcolorbox">
<pre><code>apt = read.csv(file.choose())
# apt = read.csv(&quot;~/PATH_TO_FILE/apt_around_utm.csv&quot;)

apt_model = lm(price ~ area, data = apt)</code></pre>
</div>
<p><strong>R output</strong></p>
<div class="tcolorbox">
<pre><code>&gt; apt_model

Call:
lm(formula = price ~ area, data = apt)

Coefficients:
(Intercept)       area  
     422.26       25.69  </code></pre>
</div>
<p>We can compute the residuals and the sum of squared errors (SSE) using
the table below:</p>
<div class="center">
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(y\)</span></th>
<th align="center"><span class="math inline">\(x\)</span></th>
<th align="center"><span class="math inline">\(\hat{y}\)</span></th>
<th align="center"><span class="math inline">\(y - \hat{y}\)</span></th>
<th align="center"><span class="math inline">\((y - \hat{y})^2\)</span></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">620</td>
<td align="center">11.0</td>
<td align="center">704.85</td>
<td align="center">-84.85</td>
<td align="center">7198.73</td>
<td></td>
</tr>
<tr class="even">
<td align="center">590</td>
<td align="center">6.5</td>
<td align="center">589.24</td>
<td align="center">0.76</td>
<td align="center">0.58</td>
<td></td>
</tr>
<tr class="odd">
<td align="center">620</td>
<td align="center">10.0</td>
<td align="center">679.16</td>
<td align="center">-59.16</td>
<td align="center">3499.36</td>
<td></td>
</tr>
<tr class="even">
<td align="center">700</td>
<td align="center">8.4</td>
<td align="center">638.05</td>
<td align="center">61.95</td>
<td align="center">3837.62</td>
<td></td>
</tr>
<tr class="odd">
<td align="center">680</td>
<td align="center">8.0</td>
<td align="center">627.78</td>
<td align="center">52.22</td>
<td align="center">2727.4</td>
<td></td>
</tr>
<tr class="even">
<td align="center">500</td>
<td align="center">5.7</td>
<td align="center">568.69</td>
<td align="center">-68.69</td>
<td align="center">4718.13</td>
<td></td>
</tr>
<tr class="odd">
<td align="center">760</td>
<td align="center">12.0</td>
<td align="center">730.54</td>
<td align="center">29.46</td>
<td align="center">868.17</td>
<td></td>
</tr>
<tr class="even">
<td align="center">800</td>
<td align="center">14.0</td>
<td align="center">781.92</td>
<td align="center">18.08</td>
<td align="center">327.06</td>
<td></td>
</tr>
<tr class="odd">
<td align="center">660</td>
<td align="center">7.3</td>
<td align="center">609.79</td>
<td align="center">50.21</td>
<td align="center">2520.79</td>
<td></td>
</tr>
</tbody>
</table>
</div>
<p>Recall our fitted regression model: <span class="math display">\[\hat{y} = 25.69x + 422.26\]</span></p>
<p><span class="math display">\[\text{SSE} = \sum (y_i - \hat{y}_i)^2 = 25,\!697.83\]</span></p>
<p>We now conduct a hypothesis test on the slope <span class="math inline">\(\beta_1\)</span> at the 5%
significance level.</p>
<p><strong>Step 1: Hypotheses</strong>
<span class="math display">\[H_0: \beta_1 = 0 \quad \text{vs.} \quad H_a: \beta_1 \ne 0\]</span></p>
<p><strong>Step 2: Test statistic</strong>
<span class="math display">\[s^2 = \frac{SSE}{n - 2} = \frac{25,\!697.83}{7} = 3670.26\]</span>
<span class="math display">\[s = \sqrt{3670.26} = 60.58\]</span>
<span class="math display">\[SE(\hat{\beta}_1) = \frac{s}{\sqrt{S_{xx}}} = \frac{60.58}{\sqrt{60}} = 7.82\]</span>
<span class="math display">\[t = \frac{\hat{\beta}_1 - 0}{SE(\hat{\beta}_1)} = \frac{25.69}{7.82} = 3.284\]</span></p>
<p><strong>Step 3: Conclusion</strong> Using <span class="math inline">\(t\)</span>-distribution with 7 degrees of freedom:</p>
<p><span class="math display">\[0.005 &lt; p\text{-value} &lt; 0.01\]</span></p>
<p>Since <span class="math inline">\(p\)</span>-value <span class="math inline">\(&lt; 0.05\)</span>, we reject <span class="math inline">\(H_0\)</span> and conclude that there is
sufficient evidence that <span class="math inline">\(\beta_1 \ne 0\)</span>.This suggests there is a
statistically significant relationship between price and area for
apartments near UTM.</p>
<p><strong>Final Check: Total Sum of Squares</strong></p>
<div class="center">
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(y\)</span></th>
<th align="center"><span class="math inline">\(x\)</span></th>
<th align="center"><span class="math inline">\(\hat{y}\)</span></th>
<th align="center"><span class="math inline">\((y - \hat{y})^2\)</span></th>
<th align="center"><span class="math inline">\((y - \bar{y})^2\)</span></th>
<th align="center"><span class="math inline">\((\hat{y} - \bar{y})^2\)</span></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">620</td>
<td align="center">11.0</td>
<td align="center">704.85</td>
<td align="center">7198.73</td>
<td align="center">2112.00</td>
<td align="center">1512.35</td>
<td></td>
</tr>
<tr class="even">
<td align="center">590</td>
<td align="center">6.5</td>
<td align="center">589.24</td>
<td align="center">0.58</td>
<td align="center">4850.88</td>
<td align="center">4745.68</td>
<td></td>
</tr>
<tr class="odd">
<td align="center">620</td>
<td align="center">10.0</td>
<td align="center">679.16</td>
<td align="center">3499.36</td>
<td align="center">410.73</td>
<td align="center">1512.35</td>
<td></td>
</tr>
<tr class="even">
<td align="center">700</td>
<td align="center">8.4</td>
<td align="center">638.05</td>
<td align="center">3837.62</td>
<td align="center">434.20</td>
<td align="center">1690.12</td>
<td></td>
</tr>
<tr class="odd">
<td align="center">680</td>
<td align="center">8.0</td>
<td align="center">627.78</td>
<td align="center">2727.4</td>
<td align="center">968.04</td>
<td align="center">445.68</td>
<td></td>
</tr>
<tr class="even">
<td align="center">500</td>
<td align="center">5.7</td>
<td align="center">568.69</td>
<td align="center">4718.13</td>
<td align="center">8136.08</td>
<td align="center">2524.68</td>
<td></td>
</tr>
<tr class="odd">
<td align="center">760</td>
<td align="center">12.0</td>
<td align="center">730.54</td>
<td align="center">868.17</td>
<td align="center">5133.21</td>
<td align="center">10223.46</td>
<td></td>
</tr>
<tr class="even">
<td align="center">800</td>
<td align="center">14.0</td>
<td align="center">781.92</td>
<td align="center">327.06</td>
<td align="center">1513.47</td>
<td align="center">19912.35</td>
<td></td>
</tr>
<tr class="odd">
<td align="center">660</td>
<td align="center">7.3</td>
<td align="center">609.79</td>
<td align="center">2520.79</td>
<td align="center">2410.45</td>
<td align="center">1.23</td>
<td></td>
</tr>
</tbody>
</table>
</div>
<p><span class="math display">\[SSE + SSR = SST = 25,\!697.83 + 39,\!591.06 = 65,\!288.90\]</span> This
confirms the ANOVA identity: Total = Explained + Residual</p>
<p>We previously estimated the model:</p>
<p><span class="math display">\[\hat{y} = 25.69x + 422.26\]</span></p>
<p><strong>Coefficient of Determination and Correlation</strong></p>
<p><span class="math display">\[r^2 = \frac{SSR}{SST} = \frac{39591.06}{65288.90} = 0.6063 = 60.63\%\]</span></p>
<p>Interpretation: Approximately 60.63% of the variability in price is
explained by the regression model.</p>
<p><span class="math display">\[r = \pm \sqrt{r^2} = \pm \sqrt{0.6063} = \pm 0.779\]</span></p>
<p>Since <span class="math inline">\(\hat{\beta}_1 &gt; 0\)</span>, we choose the positive root:</p>
<p><span class="math display">\[r = 0.779\]</span></p>
<p>Interpretation: There is a strong positive correlation between apartment
area and price.</p>
<p><strong>R code</strong></p>
<div class="tcolorbox">
<pre><code>model = lm(y~x, data = data\_source) 
summary(model)</code></pre>
</div>
<p><strong>R code</strong></p>
<div class="tcolorbox">
<pre><code>apt\_model = lm(price ~ area, data = apt)
summary(apt\_model)</code></pre>
</div>
<p><strong>R code</strong></p>
<div class="tcolorbox">
<pre><code>Call:
lm(formula = price ~ area, data = apt)

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)  422.256   74.834     5.643  0.00078 ***
area         25.690    7.823      3.284  0.01341 *

Residual standard error: 60.59 on 7 degrees of freedom
Multiple R-squared: 0.6064,    Adjusted R-squared: 0.5502 
F-statistic: 10.78 on 1 and 7 DF,  p-value: 0.01341</code></pre>
</div>
<p><strong>Two-sided Test for Slope Coefficient</strong></p>
<p>By default, R performs a two-sided test:
<span class="math display">\[H_0: \beta_1 = 0 \quad \text{vs.} \quad H_a: \beta_1 \neq 0\]</span></p>
<p>Test statistic:
<span class="math display">\[t^* = \frac{\hat{\beta}_1 - 0}{SE(\hat{\beta}_1)} = \frac{25.690 - 0}{7.823} = 3.284\]</span></p>
<p><span class="math display">\[t^* \sim t_{(n - 2)}  \quad \text{with } df = 9 - 2 = 7\]</span></p>
<p><strong>p-value</strong> is the total shaded area in both tails. From R output:
<span class="math display">\[\text{p-value} = 0.01341\]</span></p>
</div>
</div>
<div class="definition">
<p><span id="def:unlabeled-div-111" class="definition"><strong>Definition 9.9  </strong></span></p>
<ul>
<li><p><strong>Interpolation</strong> is calculating predicted values of <span class="math inline">\(y\)</span> using our
linear model while working within the range of <span class="math inline">\(x\)</span> in which data was
available to construct our model.</p></li>
<li><p><strong>Extrapolation</strong> is calculating predicted values of <span class="math inline">\(y\)</span> using our
linear model outside the range of <span class="math inline">\(x\)</span> used to obtain the linear model.</p></li>
<li><p>Interpolation is usually safe if we have a good linear model.</p></li>
<li><p>Extrapolation must be performed carefully since extrapolations that
are done without any foresight can be very inaccurate.</p></li>
</ul>
</div>
</div>
<div id="residual-plots" class="section level3 hasAnchor" number="9.2.4">
<h3><span class="header-section-number">9.2.4</span> Residual Plots<a href="simple-linear-regression.html#residual-plots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Residual plots are used to verify assumptions related to the error terms
in a regression model.</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1 X + \varepsilon, \quad \varepsilon \sim \mathcal{N}(0, \sigma^2)\]</span></p>
<p>The assumption <span class="math inline">\(\varepsilon \sim \mathcal{N}(0, \sigma^2)\)</span> implies:</p>
<ul>
<li><p>Mean of errors is 0</p></li>
<li><p>Constant variance of errors (homoscedasticity)</p></li>
</ul>
<p>We plot the residuals: <span class="math display">\[e_i = y_i - \hat{y}_i\]</span> against the fitted
values <span class="math inline">\(\hat{y}_i\)</span> to assess these assumptions.</p>
<!-- ### What to Look for in a Good Residual Plot {#what-to-look-for-in-a-good-residual-plot .unnumbered} -->
<p>If the assumption <span class="math inline">\(\varepsilon \sim \mathcal{N}(0, \sigma^2)\)</span> is
satisfied, the residual plot should have the following features:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Random scattering:</strong> No obvious pattern in residuals.</p>
<ul>
<li><p>A pattern (e.g., curve) may indicate a non-linear relationship.</p></li>
<li><p>Random scattering also suggests independence of errors.</p></li>
</ul></li>
<li><p><strong>Constant variance:</strong> Residuals should fall within a horizontal
band, roughly half above and half below zero.</p>
<ul>
<li>Suggests constant variance (homoscedasticity).</li>
</ul></li>
<li><p><strong>No influential points or clustering:</strong> The plot should not show
isolated influential observations or clustering.</p></li>
</ol>
<!-- # ```{r residual-stack, fig.width=6, fig.height=16, dev="png", out.width="100%", fig.align="center", message=FALSE, warning=FALSE} -->
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-31"></span>
<img src="Book_Files/figure-html/unnamed-chunk-31-1.png" alt="Examples of residual plots which satisfy assumpations and which violate assumptions" width="70%" />
<p class="caption">
Figure 9.11: Examples of residual plots which satisfy assumpations and which violate assumptions
</p>
</div>
<div class="tcolorbox">
<p>The model is: <span class="math inline">\(Y = \beta_0 + \beta_1 X + \varepsilon\)</span>, where
<span class="math inline">\(\varepsilon \sim \mathcal{N}(0, \sigma^2)\)</span></p>
<ul>
<li><p>The relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is linear.</p></li>
<li><p>Residuals:</p>
<ul>
<li><p>are independent</p></li>
<li><p>have constant variance</p></li>
<li><p>are normally distributed</p></li>
</ul>
<p>These assumptions can be verified using residual plots.</p></li>
</ul>
</div>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="analysis-of-variance.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="analysis-of-categorical-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": true,
    "facebook": false,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
